### ISSUE TITLE
Aqara door sensor isn’t registering open or close in HomeKit

### ISSUE THREAD

**Issue by Drag0n** [robertklep/name.klep.homekitty#10]
### Type (brand/model) of device
Aqara Door and Window Sensor
MCCGQ11LM

### Is it supported by HomeyKit?
No

### Device Classes

* _Class_: -
* _Virtual Class_: -

### Device Capabilities

* ID:alarm_contact | Title: Contact alarm | Type: boolean
* ID:alarm_battery | Title: Battery alarm | Type: boolean
* ID:measure_battery | Title: Battery | Type: number

**Comment by robertklep** [comment]
A device has to have a device class, I'm guessing it's "sensor"?

**Comment by basvdploeg** [comment]
@Drag0n Just to be sure... This is my configuration. If yours is the same, I doubt that HomeKitty is the problem.

<img width="744" alt="Scherm­afbeelding 2022-12-07 om 20 13 35" src="https://user-images.githubusercontent.com/4628469/206275048-1a0fdfcd-6123-4c27-a725-d528fe459952.png">

**Comment by robertklep** [comment]
@basvdploeg you're still using the Github version of the app, right? That might be the reason (although I'm fairly sure that this type of sensor should be supported by the current test version).

If the Github version is still working fine, I'll push it to the store.

**Comment by robertklep** [comment]
@Drag0n are you sure the device is working okay in the Homey app?

**Comment by robertklep** [comment]
@Drag0n also, it sometimes takes quite long for the Home app to show the updated status of the sensor, which is very annoying (this is really an issue with Apple's Home app, I use [Home+](https://hochgatterer.me/home+/) myself which shows the updated status a lot quicker).

**Comment by Drag0n** [comment]
> A device has to have a device class, I'm guessing it's "sensor"?

Sorry my bad, yes class is sensor

**Comment by Drag0n** [comment]
> @Drag0n are you sure the device is working okay in the Homey app?

yes, I'm now using the Homey Flows to automate things.

**Comment by Drag0n** [comment]
> @Drag0n also, it sometimes takes quite long for the Home app to show the updated status of the sensor, which is very annoying (this is really an issue with Apple's Home app, I use [Home+](https://hochgatterer.me/home+/) myself which shows the updated status a lot quicker).

yeah I use different apps also to do advanced automations. Use the Eve app but it's the same, and Controller app too.

**Comment by robertklep** [comment]
@Drag0n all I can say is that the device is supported, so this is a local issue. Can you create a diagnostics report? (in the Homey mobile app, go to "More > Apps > HomeKitty", press the gear symbol in the top right corner, and press "Create diagnostics report").

**Comment by robertklep** [comment]
According to the diagnostics report, all sensors are supported and working. For example:
```
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] capability update - capability=alarm_contact raw=true
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] - update characteristic - name = ContactSensorState value = 1
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] capability update - capability=alarm_contact raw=false
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] - update characteristic - name = ContactSensorState value = 0
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] capability update - capability=alarm_contact raw=true
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] - update characteristic - name = ContactSensorState value = 1
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] capability update - capability=alarm_contact raw=false
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] - update characteristic - name = ContactSensorState value = 0
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] capability update - capability=alarm_contact raw=true
[HomeKitty] [Bathroom Door Sensor - Service.ContactSensor] - update characteristic - name = ContactSensorState value = 1
```

Do you perhaps have an old Home hub (iPad/Apple TV) that might be causing this issue?

**Comment by Drag0n** [comment]
I disconnected all hubs with the latest iOS (16.1.1) and used an old iPads that’s on iOS 15.7. Problem resolved, so it’s definitely an iOS 16 issue.

**Comment by robertklep** [comment]
Ah, good to hear you found the cause 👍🏻
