### ISSUE TITLE
[Feature Request/Unsupported] Mitsubishi app of evdpol does not fully work

### ISSUE THREAD

**Issue by thatsme24u** [robertklep/name.klep.homekitty#102]
(make sure you also edit the title)

I can chose in home app cool heat auto of but it does not turn in or off the airco.
When the airco is turned on via the m air app, It is on in Homey but not in home.
There is indeed communication: changing the temp in home actually changes the airco temp. and the actual room temp is showde in home.

### Type (brand/model) of device
Mitsubishi SRK 25 ZS-WF (standaard model with wf RAC module)
...

### Homey Model
- [ ] "old" Homey (Pro)
- [ X] Homey Pro 2023

### Is it supported by HomeyKit?
- [ X] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: thermostat
* _Virtual Class_: xxx

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID	Title	Type	Value	Set Value	Last Changed
measure_temperature.outdoor	Buitentemperatuur	number	20.7		9 minutes ago
measure_temperature	Binnentemperatuur	number	28.7		9 minutes ago
target_temperature	Ingestelde temperatuur	number	24	SET 23 hours ago
onoff	Aangezet	boolean	false	SET 11 hours ago 
operating_mode	Werkingsmodus	enum	cool	SET 23 hours ago
fan_speed	Ventilatorsnelheid	enum	auto	SET 23 hours ago
vertical_position	Verticale luchtstroom	enum	middle	SET 23 hours ago
horizontal_position	Horizontale luchtstroom	enum	center-right	SET 11 hours ago
3d_auto	3D AUTO	boolean	false	SET 23 hours ago

* ...
* ...
* ...
Thanks for investigating robert

**Comment by robertklep** [comment]
The issue is that the device is presented as a thermostat, and in HomeKit thermostats don't have an on/off state.

Homey has a specific capability for thermostats (`thermostat_mode`) that HomeKitty supports, but the Mitsubishi app doesn't. Instead, it looks like it implemented its own logic based on `onoff` and a custom capability `operating_mode`.

In other words: I can't really fix this in HomeKitty because the Mitsubishi doesn't implement the "regular" capabilities for thermostats in Homey, and HomeKitty is unable to support custom app logic.

**Comment by thatsme24u** [comment]
Hi Robert, I am convinced you know way better then me how things are working. ...
But currently I use a Tada smart airco remote. 
This one is also thermostat.  

Any idea how that one is working fine in home?

I can set this one: uit - verwarmen or koelen 


ID	fb5f162f-0696-4595-9d08-cf5054a830a0
Name	Huiskamer - Slimme Aircobediening
Class	thermostat
Driver	homey:app:com.tado2:airconditioning
Ready	Yes
Available	Yes
Warning	No
Custom icon	No

Data
Key	Value
id	"WR1509570304"

Settings
Key	Value
serialNumber	"WR1509570304"
overlayMode	"MANUAL"
timerDuration	10
climate_exclude	false

Capabilities
ID	Title	Type	Value	Set Value	Last Changed
target_temperature	Ingestelde temperatuur	number	25	


SET
21 hours ago
measure_temperature	Temperatuur	number	27		4 minutes ago
measure_humidity	Luchtvochtigheid	number	61.6		4 minutes ago
ac_mode	Modus	enum	OFF	


SET
20 hours ago
fan_level	Ventilator niveau	enum	AUTO	


SET
3 weeks ago
vertical_swing	Verticale swing	enum	MID	


SET
6 days ago
horizontal_swing	Horizontale swing	enum	RIGHT	


SET
4 weeks ago
detect_open_window	Open raam detectie	boolean	false		7 months ago

**Comment by robertklep** [comment]
HomeKitty requires (at least) two capabilities for thermostats to make it work with Home: `measure_temperature` and `target_temperature`.

The Mitsubishi app uses those two, but my guess is that when it gets turned on, it doesn't set those capabilities explicitly which means HomeKitty has no idea that the "thermostat" was turned on and nothing changes in Home (HomeKitty doesn't support `onoff` capabilities for thermostats). My guess is also that when you turn on the Mitsubishi device and then change the target temperature, it will update its status in Home.

The Tado implementation will be different in such a way that it does work.

**Comment by thatsme24u** [comment]
Thans for explanation Robert!
