### ISSUE TITLE
[Feature Request] Prevent button being published to HomeKit

### ISSUE THREAD

**Issue by bursacmilan** [robertklep/name.klep.homekitty#103]
### Type (brand/model) of device
Aqara Door and Window Sensor P2

### Homey Model
- [ ] "old" Homey (Pro)
- [X] Homey Pro 2023

### Is it supported by HomeyKit?
- [X] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: sensor
* _Virtual Class_: -

### Device Capabilities

* button.remove_node, Remove Matter Node, boolean
* alarm_contact, Contact alarm, boolean

---

I'm referencing this issue: https://github.com/robertklep/name.klep.homekitty/issues/97#issuecomment-2308100175

I'm using the new Aqara P2 Door Sensor, connected via Matter with my HomeyPro (without using any app). While it generally works well, I'm encountering a problem in HomeKit where two devices appear:

1. **Contact Sensor** — This is the functionality I need.
2. **Switch** — This seems unnecessary. When I toggle the switch, the P2 sensor is removed from my Matter network, requiring a re-pairing process.

After investigating the device's capabilities, I found it has two main functions:
- `alarm_contact`: Contact alarm
- `button.remove_node`: Remove Matter Node

This explains why a switch appears in HomeKit and why the device gets removed when the switch is activated. Is there a way to prevent the switch from being published to HomeKit?

**Comment by robertklep** [comment]
Oh geez, someone (at Athom I presume) has thought it would be a good idea to give Matter devices a `button` capability that, when pressed, removes the device from Homey 🤦🏼‍♂️

I'll try and see if I can easily filter away these capabilities so they don't get published to iOS.

**Comment by robertklep** [comment]
Should be fixed in v2.2.18, [the current test version](https://homey.app/a/name.klep.homekitty/test/).

**Comment by robertklep** [comment]
@bursacmilan can you do me a favour and run this HomeyScript on your Homey?

```
const devices = await Homey.devices.getDevices();

for (const [ id, device ] of Object.entries(devices)) {
  if (! device.capabilities.includes('button.remove_node')) continue;
  console.log(device);
}
```

The `button.remove_node` capability might be flagged as "special", which means I can make the check that I implemented more generic by always skipping these special capabilities.

I don't have any devices with these capabilities so I cannot see for myself how exactly they are marked.

**Comment by bursacmilan** [comment]
Yes, I don’t understand why they implemented that either! 😄 Thanks for the fix!

**Comment by robertklep** [comment]
@bursacmilan can you try the current latest test version (v2.3.0)? It uses a different way of determining which capabilities should be mapped, and it should prevent _any_ special capabilities from being exposed to iOS.

**Comment by bursacmilan** [comment]
@robertklep I tested the version, and it works perfectly. I'm now only seeing the sensor, and the switch has been removed. Thanks a lot!
