### ISSUE TITLE
[Unsupported] Danfoss Radiator Valve

### ISSUE THREAD

**Issue by wf-dekker** [robertklep/name.klep.homekitty#106]
(make sure you also edit the title) ✔️

### Type (brand/model) of device
Danfoss Radiator Valve LC13

### Homey Model
- [ X ] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ X ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: thermostat
* _Virtual Class_:doesnt have

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* target_temperature	Target temperature	number
* measure_battery	Battery	number
* alarm_battery	Battery alarm	boolean

**Comment by robertklep** [comment]
A thermostat device in HomeKit requires a `measure_temperature` capability, which your device doesn't have 🙁

**Comment by wf-dekker** [comment]
Ah that makes sense. I was already wondering why it wasn’t supported in homeykit before.

**Comment by robertklep** [comment]
It might be possible to create a virtual thermostat using the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) that "follows" your radiator valve and has an additional `measure_temperature` capability (based on a temperature sensor in the same room), and expose that virtual thermostat to HomeKit.

However, I haven't used this app extensively myself so I can't help with setting this up, but its developer and other users of the app are quite active on the [Homey forum](https://community.homey.app/).

I'll close this issue for now 😅

**Comment by wf-dekker** [comment]
Yes creating a virtual thermostat and making some flows to update to and from it works very well! Good workaround!
