### ISSUE TITLE
request/Unsupported Device to motorized window

### ISSUE THREAD

**Issue by 9leo** [robertklep/name.klep.homekitty#107]
### Type virtual device 

hi, i searched but i couldn't find anything, i wanted to know if it was possible to implement the motorized window as a device, eg velux. i had the possibility in homekit via the velux gateway, but once i inserted it in homey via homekitcontroller i can't export it to homekitty because the device class is not supported. i created a virtual curtains device to get around the problem but the icon in homekit doesn't match, the original one was the ceiling window with open closed animation, i couldn't find it online, if it were needed i'll re-pair it with homekit and i'll attach a photo in case i didn't understand which one i'm referring to.

### Homey Model
- [ ] "old" Homey (Pro)
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [x] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: other
* _Virtual Class_: 

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* windowcoverings_set
* position
* number

**Comment by robertklep** [comment]
Can you try this? https://homey.app/a/name.klep.homekitty/test/

**Comment by 9leo** [comment]
It seems to work, the only thing is that the device class is not correct, there is a curtain in homekit instead of the window category, I attach the corresponding icons. Thanks anyway, I'll test it for a few days and let you know.
![IMG_5343](https://github.com/user-attachments/assets/2316d4f4-49c5-43f1-8dc1-af03b4d1900e)
![IMG_5344](https://github.com/user-attachments/assets/5b481a5b-aa03-4162-9627-8ec2cf43e3b4)

**Comment by robertklep** [comment]
The information that Homey provides is not enough for HomeKitty to determine the type of device (window, curtain, blinds, etc), so they are all presented to Home as "window covering".
