### ISSUE TITLE
Unsupported device that worked in you earlier HomeKit app

### ISSUE THREAD

**Issue by Laro1979** [robertklep/name.klep.homekitty#108]
Type (evcharger / brand =Charge Amps) of device
...

### Homey Model
- [x] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [x ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID | Title | Type |
measure_aura1 | AURA1: Effekt | number 
meter_aura1 | AURA1: Energi | number 
measure_aura2 | AURA2: Effekt | number
meter_aura2 | AURA2: Energi | number
measure_both | Total: Effekt | number
meter_both | Total: Energi | number
aura1onoffButton | AURA1: Tænd/Sluk | boolean
aura2onoffButton | AURA2: Tænd/Sluk | boolean
aura1RFIDButton | AURA1: RFID Tænd/Sluk | boolean
aura2RFIDButton | AURA2: RFID Tænd/Sluk | boolean
aura1CableLockButton | AURA1: Kabellås | boolean
aura2CableLockButton | AURA2: Kabellås | boolean
auraLEDringButton | LED Ring niveau | enum
aura1onoffStatus | AURA1: Status | string
aura2onoffStatus | AURA2: Status | string
aura1CarConnected | AURA1: Tilstand | string
aura2CarConnected | AURA2: Tilstand | string
aura1CurrentLimit | AURA1: Strømbegrænsning (A) | number
aura2CurrentLimit | AURA2: Strømbegrænsning (A) | number
aura1LastCharged | AURA1: Sidste opladning kWh | string
aura2LastCharged | AURA2: Sidste opladning kWh | string
Setharged | AURA1: Nu opladet kWh | string
aura2NowCharged | AURA2: Nu opladet kWh | string
auraFW | FW Version | string | null
auraVersion | Charger version | string | null
aura1RFIDStatus | AURA1: RFID-status | string
aura2RFIDStatus | AURA2: RFID-status | string
aura1CableLockStatus | AURA1: Kabellås | string
aura2CableLockStatus | AURA2: Kabellås | string
auraLEDringStatus | LED Ring | string

**Comment by robertklep** [comment]
I'm fairly sure this device wasn't supported by HomeyKit either, given that it only uses custom capabilities, which were never supported.

Are you sure that it was supported? And if so, how exactly? As what type of device did it present itself in iOS?

**Comment by Laro1979** [comment]
HiIt was supported and presented itself in Apple HomeKit as an switch so I could turn on and off, but it only turned on the left charge port on my charger. I have the Charge Amps Aura that has 2 charging ports.Could it be that the Charge Amps app is updated and therefore doesn’t work anymore?Best regards Lars HåkanSendt fra min iPhoneDen 27. sep. 2024 kl. 07.13 skrev Robert Klep ***@***.***>:﻿
I'm fairly sure this device wasn't supported by HomeyKit either, given that it only uses custom capabilities, which were never supported.
Are you sure that it was supported? And if so, how exactly? As what type of device did it present itself in iOS?

**Comment by Laro1979** [comment]
Any way to get it supported again like a switch like it used to?Should I contact the developer of the Charge Amps app?Best regards Lars HåkanSendt fra min iPhoneDen 27. sep. 2024 kl. 09.09 skrev Robert Klep ***@***.***>:﻿
Yes, it could be that this is caused by an app update. I don't see any capabilities that are supported by either HomeKitty or HomeyKit.

**Comment by robertklep** [comment]
Not directly by HomeKitty, the Charge Amps app only uses custom capabilities and those aren't supported.

You can try using the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) to create a virtual device based on your charger, and expose that virtual device to HomeKit, but I can't really help with that.
