### ISSUE TITLE
Homey Pro automatic update to 12.2.0 Homekitty all devices not responding in HomeKit

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [robertklep/name.klep.homekitty#109]
The title pretty much sums it up. Last night Homey Pro did an automatic update after which all devices exposed to HomeKit via Homekitty are not responsing. All devices are usable in Homey Pro. Is this a known issue or is there a fix to the issue? Rebooting HomeKit hubs, router and accespoints,Homekitty app and Homey pro did not fix the issue.

**Comment by robertklep** [comment]
Can you restart the app, then generate a diagnostics report for it?

**Comment by AllSeeingGoatWizard** [comment]
Hi,the problem seems to have fixed itself. I rebooted everything in my network several times and everything came back online. Atte EngrenRobert Klep ***@***.***> kirjoitti 7.11.2024 kello 16.31:﻿
Can you restart the app, then generate a diagnostics report for it?
