### ISSUE TITLE
Homekitty iOS 16.2 ready ?

### ISSUE THREAD

**Issue by Dici71** [robertklep/name.klep.homekitty#11]
Hi,

it seems that iOS 16.2 will be released soon. is Homekitty ready for it ? Or is it better to wait to upgrade ?

**Comment by robertklep** [comment]
It should be, yes, but I don't run iOS prereleases so can't test out myself.

**Comment by Dici71** [comment]
ok...i´ll test it when iOS16.2 will be released as final and let you know if you want ?

**Comment by robertklep** [comment]
I will probably update to 16.2 quite soon after it gets released, but more tests is always better!

**Comment by basvdploeg** [comment]
HomeKitty runs fine on 16.2. 

I even updated to the new HomeKit architecture, and everything works as expected.

**Comment by Dici71** [comment]
sounds good....thanks for the information !
