### ISSUE TITLE
Target temperature fixed to 10°C?

### ISSUE THREAD

**Issue by christiaandewit** [robertklep/name.klep.homekitty#112]
It seems to me that the minimum target temperature for a thermostat in Home Kit is always 10°C, even when the thermostat in Homey allows a lower target temperature. I've tested this with Vtherm and Virtuele Apparaten and the result in Home Kit is the same.

In my case, I have a electric heaters in my garage and storage connected to an Ikea smart plug and the temperature is measured by Sonoff temperature sensors. I added a virtual thermostat using the Vtherm Homey app and it works perfectly fine, except for the minimum target temperature. I've set it to 5°C in Homey, but in the Home app it shows a target temperature of 10°C. 

@robertklep, am I doing something wrong? If you need more information, please ask.

**Comment by robertklep** [comment]
Yes, the default minimum target temperature in Homekit is 10°C. I'll see if I can transfer the values from the Homey capability over to the Homekit characteristics.

**Comment by robertklep** [comment]
Try the test version: https://homey.app/a/name.klep.homekitty/test/

**Comment by christiaandewit** [comment]
Now HomeKit shows the correct target temperature. I still cannot change it to a value lower than 10°C, but as I understand it correctly, that's a limitation of HomeKit itself?

**Comment by christiaandewit** [comment]
While searching the internet, I stumbled upon a forum for OpenHab, where a similar issue was discussed. It seems like there might be a solution: https://community.openhab.org/t/minimum-and-maximum-temperature-for-homekit-binding-thermostat/17442
However, I'm not a developer, so maybe I'm completely off here 🤷‍♂️

**Comment by robertklep** [comment]
It should be possible to set it lower:
<img width="266" alt="image" src="https://github.com/user-attachments/assets/e93fdfe0-0140-4fb2-863e-dc94ee5246b8">
(4°C is the default minimum for the Homey capability, so it got transferred properly to Homekit)

You can try to "unpublish" the device, then publish it again. You can do that from the app configuration screen for Homekitty in the Homey app.

**Comment by robertklep** [comment]
Thanks for testing! 👍🏻
