### ISSUE TITLE
Flow Starter or Aqara T2 as Garage Door?

### ISSUE THREAD

**Issue by FrankR255** [robertklep/name.klep.homekitty#115]
If got an Aqara T2 and it shows in HomeKit as a switch or fan.
Is it possible to show it as Garagedoor or an Flow starter as Garagedoor?
I would like to use the device in Carplay.

### Type (brand/model) of device
Aqara T2 or Flow Starter

### Homey Model

Homey Pro 2023

### Is it supported by HomeyKit?
Yes

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

Property | Value
-- | --
ID | 6f98da54-d0ec-4420-8ae7-24707dc3a7a8
Name | Doppelrelais-Modul T2
Class | socket
Driver | homey:app:com.xiaomi-mi:switch.acn047

token | "cbfb229f-9361-4f0e-8243-f21c58fb2789"

zb_product_id | "lumi.switch.acn047"
zb_manufacturer_name | "Aqara"
zb_receive_when_idle | "✓"
zb_device_type | "router"
zb_ieee_address | "54:ef:44:10:00:cd:b2:b5"
zb_sw_build_id | "0.0.0_0028"
zb_touchlink_group_ids | ""
save_state | "1"
switch_type | "2"
switch_operation_mode_S1 | true
switch_operation_mode_S2 | true
interlock_mode | false
device_operation_mode | "1"
pulse_length | 0.2
energy_alwayson | false

**Comment by robertklep** [comment]
As far as I know, neither is possible (this is a limitation of Homekit itself). Perhaps it's possible to create a virtual device in Homey (for instance with the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) (it would need to be of device class `garagedoor` and have the `garagedoor_closed` capability).

**Comment by FrankR255** [comment]
Thx for your awnser.
I will try it.

**Comment by FrankR255** [comment]
Now your App found my Inverter.
After a reinstall.
Logs ar send to you.
Maybe you have a look on it

**Comment by FrankR255** [comment]
Hi,
I tried around a bit. With the DeviceCapabilities app I can simulate a garage, but Homekitty says that the device is not supported. Do you have any tips?

**Comment by robertklep** [comment]
HomeKitty only supports devices of class `garagedoor` that have the capability `garagedoor_closed`, so make sure it has one.

**Comment by FrankR255** [comment]
It has the  class garagedoor and the capability garagedoor_closed.button

**Comment by FrankR255** [comment]
Thx

**Comment by robertklep** [comment]
Working as expected:
<img width="163" alt="image" src="https://github.com/user-attachments/assets/f70d9623-8c4d-451b-8b67-2478657e08ce">

However, the capability is showing differently for me:
<img width="531" alt="image" src="https://github.com/user-attachments/assets/91fe0c02-a19d-4150-a254-7f2ecf9c572f">

You have to enable the "Create Real Field and Flowcards" setting:
<img width="363" alt="image" src="https://github.com/user-attachments/assets/f2682c12-13e0-4c02-9375-d413dca04a62">

**Comment by robertklep** [comment]
Oh and make sure you're running the test version of the app: https://homey.app/a/name.klep.homekitty/test

**Comment by FrankR255** [comment]
Ok with the Testversion it works.
Thanks
