### ISSUE TITLE
[Feature Request/Unsupported]

### ISSUE THREAD

**Issue by SterkeYerke** [robertklep/name.klep.homekitty#116]
Bold smart lock working in Homey, but not shown in Homekit via Homekitty

### Type (brand/model) of device
Blod smart lock and smart cylinder

### Homey Model
- [ ] "old" Homey (Pro)
- [x ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [ x] I don't know

### Device Classes
lock

What are it's class, and virtual class (if it has one)?

lock
n.a.

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ID : onoff
* Tiltle: aangezet
* Type value: boolean false
* Set value: false
* last changed: 11 minutes ago

**Comment by robertklep** [comment]
It should be supported already, try installing the test version of the app: https://homey.app/a/name.klep.homekitty/test/

**Comment by robertklep** [comment]
Does the device appear in the list of devices on the app settings page? It's probably listed under "Not Added", in which case you can add it and it should appear on iOS.

By the way, your phone number is appearing in your comment, which is public. I'll edit the comment and remove it, but please be aware of this.

**Comment by robertklep** [comment]
At the moment all development is being done on the test version of the app. I always try to make sure that the test app doesn't break anything, so you should be able to run the test version indefinitely.

But at some point I will upgrade the test version to the next stable, at which point you should be able to move back to the stable version without issues, if you want to.
