### ISSUE TITLE
aqara mini switch not exposed to homekit

### ISSUE THREAD

**Issue by SterkeYerke** [robertklep/name.klep.homekitty#117]
(make sure you also edit the title)

### Type (brand/model) of device
Aqara mini switch

### Homey Model
- [ ] "old" Homey (Pro)
- [ x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [ x] I don't know, but is worked via homebridge

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:              button
* _Virtual Class_:  n.a.

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* alarm_battery;  Batterij-alarm;  boolean
* measure_battery; Accuniveau; number
* ...

In the Homekitty list of supported devices it is listed in the 'not supported' list.

**Comment by robertklep** [comment]
The device only has "reporting" capabilities, no control capabilities, so there's nothing that HomeKitty can do with it.
