### ISSUE TITLE
Honeywell home evoTouch not exposed to homekit

### ISSUE THREAD

**Issue by SterkeYerke** [robertklep/name.klep.homekitty#118]
(make sure you also edit the title)

### Type (brand/model) of device
Honeywell hove evoTouch

### Homey Model
- [ ] "old" Homey (Pro)
- [ x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x ] I don't know, it was working fine via homebridge

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:               other
* _Virtual Class_:   n.a.

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* alarm_battery; Batterij-alarm; boolean
* honeywell_thermostat_mode; Thermostatmodus; enum; possible values (auto, heatingOff, away, autoWithEco, custom, dayOff)
* ...

all Evohome zones (thermostats) are exposed perfectly fine, only the central console is not shown.

**Comment by robertklep** [comment]
This device uses a custom capability (`honeywell_thermostat_mode`) that HomeKitty doesn't (and cannot) support.
