### ISSUE TITLE
Sonos speakers show up as 'not supported' in Apple Home, able to make a switch on/off for play/pause? Thx! :-)

### ISSUE THREAD

**Issue by NiWis89** [robertklep/name.klep.homekitty#119]
(make sure you also edit the title)

### Type (brand/model) of device
Sonos Play1 (2x) (1st gen)
Sonos Playbar (1st gen)
Sonos Arc (1st gen)

### Homey Model
- [ ] "old" Homey (Pro)
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [x] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: speaker
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* speaker_playing
* ...
* ...

![IMG_2662](https://github.com/user-attachments/assets/2979abb4-c3c9-451f-acc1-65c418e9c665)

**Comment by robertklep** [comment]
I'm afraid it's not possible to implement speaker support with HomeKitty. See also [here](https://github.com/robertklep/name.klep.homekitty/issues/94#issuecomment-2384859291).

**Comment by NiWis89** [comment]
Hi Robert, thank you for getting back to me so quickly :-) I've also checked the other case and it's identical to my situation indeed. Unfortunately this is not supported by Apple Home. 

One idea: my Samsung Smartthings TV shows up as a on/off switch (as you can see on print screen) via Homekitty. Perhaps it's possible to create a switch like this for Sonos as well just for play/pause? Probably though too easy, but you never know. Thanks :-)

**Comment by robertklep** [comment]
You can use a virtual device for this, like the Virtual Socket device that Homey has built-in, or otherwise using the [Virtual Devices app](https://homey.app/a/com.arjankranenburg.virtual/).

**Comment by NiWis89** [comment]
Yes I had the same idea. I have tried creating a virtual device (mode) via the Virtual Devices app, but I'm having issues with automatically stop/play loops with the speakers, probably caused by the flows I've connected:

- VD turned on -> speaker play
- VD is being turned on (by other controller) -> VD on without trigger
- VD is being turned off (by other controller) -> VD off without trigger
- VD turned off -> speaker pause

As you can see on printscreen below Homey triggers play pause in a loop on random times, sometimes it works perfect but at random moments the loop start. Therefore I was looking for a direct integration of Sonos without VD's, maybe there's something wrong with the flows?

![IMG_2713](https://github.com/user-attachments/assets/3556c97c-d94d-4959-b8a0-541785e30cd0)

**Comment by robertklep** [comment]
You probably want something like this:
* VD turned on -> speaker play
* Speaker turned on -> VD on without trigger
* Speaker paused -> VD off without trigger
* VD turned off -> speaker pause

**Comment by NiWis89** [comment]
That's exactly how I have the flows set up. Can it perhaps be caused by the VD being a 'mode' instead of a 'device'? Thanks for the help, really appreciate it!

**Comment by robertklep** [comment]
You'd have to try if it works as a device, I don't know VD too well.

**Comment by NiWis89** [comment]
Oke thanks, I'll try some things. Thank you for the help!
