### ISSUE TITLE
How to expose tilt control of Fibaro Roller Shutter 3 to Apple Home via Homey Pro?

### ISSUE THREAD

**Issue by wokim** [robertklep/name.klep.homekitty#120]
I'm controlling a slat-adjustable shutter blind using Fibaro Roller Shutter 3 connected to Homey Pro. While both position and slat tilt controls work perfectly in Homey, I'm facing an issue with Apple Home integration.

I'm using the Homekitty app to expose my blinds to Apple Home (since Homey Pro's native HomeKit integration doesn't seem to support blinds yet). While this works great for basic functionality, I can't control the slat tilt angle in Apple Home - it only shows and controls the position.

Device Details:
* Class: windowcoverings (Virtual: shutterblinds)
* Driver: homey:app:com.fibaro:FGR-223

Capabilities:
| ID | Title | Type | Value | Set | Last Changed |
|---|---|---|---|---|---|
| windowcoverings_set | Position | number | 0 | Set | 19 minutes ago |
| measure_power | Power | number | 0 | - | 18 minutes ago |
| meter_power | Energy | number | 1.483 | - | 38 minutes ago |
| windowcoverings_tilt_set | Window Coverings Tilt Set | number | 0.5 | Set | 4 minutes ago |

Is there a way to expose both position and tilt control to Apple Home? Any suggestions would be appreciated.

**Comment by wokim** [comment]
I just discovered https://github.com/robertklep/name.klep.homekitty/pull/104 PR and realized it was already deployed in version `2.3.1`. 

The tilt angle control works perfectly in `test version 2.3.5`, while it's not available in the current `stable release 2.2.7`.

Thank you so much for implementing this feature. Closing this issue.

**Comment by robertklep** [comment]
I was just going to ask if you were running the test version 😁
