### ISSUE TITLE
thermostat can't change mode

### ISSUE THREAD

**Issue by gliwot** [robertklep/name.klep.homekitty#15]
Hi, I have different kinds of thermostat devices and all can change Celcius value if mode is already on but can't change the mode from off to heat or other way around. 

### Type (brand/model) of device
MCO Home
Gree

### Is it supported by HomeyKit?
Partly

### Device Classes
(find the device [here](https://tools.developer.homey.app/tools/devices) and post its class and virtual class, if it has one)

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...
* ...
* ...

**Comment by robertklep** [comment]
The questions about device classes and capabilities aren't optional 😉 I need more information if you want me to look at your issue.

**Comment by gliwot** [comment]
Sure thing. Had the same issue with HomeyKit.
Class: thermostat

For MCOHome
ID | Title | Type | Value | Set Value | Last Changed
-- | -- | -- | -- | -- | --
measure_temperature | Temperature | number | 17.9 |   | 2 minutes ago
measure_humidity | Humidity | number | 42 |   | 2 minutes ago
thermostat_mode_custom | Thermostat mode | enum | Off | HeatEnergy Save HeatOffAWAYSETUNSET | 6 days ago
thermostat_onoff | State | boolean | false |   | 2 months ago
target_temperature | Target temperature | number | null | SETUNSET | 6 days ago

For Gree


ID | Title | Type | Value | Set Value | Last Changed
-- | -- | -- | -- | -- | --
onoff | Turned on | boolean | true | truefalseSETUNSET | 29 minutes ago
measure_temperature | Temperature | number | null |   |  
target_temperature | Target temperature | number | 16 | SETUNSET | 3 weeks ago
thermostat_mode | HVAC mode | enum | heat | autocoolheatdryfan_onlySETUNSET | 3 weeks ago
fan_speed | Fan speed | enum | auto | autolowmediumLowmediummediumHighhighSETUNSET | 3 weeks ago
turbo_mode | Turbo mode | boolean | false | truefalseSETUNSET | 1 month ago
lights | Lights mode | boolean | true | truefalseSETUNSET | 1 month ago
xfan_mode | X-Fan mode | boolean | null | truefalseSETUNSET |  
vertical_swing | Vertical swing | enum | fixedTop | defaultfullfixedTopfixedMidTopfixedMidfixedMidBottomfixedBottomswingBottomswingMidswingTopSETUNSET | 3 weeks ago

Hope this helps since I am a little bit clueless as you can see :)

**Comment by robertklep** [comment]
The MCO Home thermostat uses custom capabilities (which are unique to the application) for its state and mode, and custom capabilities aren't supported by HomeKitty (or HomeyKit).

The Gree thermostat should be _somewhat_ supported because it has all the capabilities that are required for HomeKitty to implement a thermostat device. What specifically is your problem with this device in combination with HomeKitty?

**Comment by gliwot** [comment]
Both have the same issue. I cannot turn them on or off using homekit, but if they are already turned on, then I can change temperature without a problem.

**Comment by robertklep** [comment]
Oh sorry, I just noticed that the Gree thermostat doesn't use the regular `thermostat_mode` implementation but also a custom one, so HomeKitty can't support that either.
