### ISSUE TITLE
Unsuported Device: POPP Flow Stop 2

### ISSUE THREAD

**Issue by MNHPetersen** [robertklep/name.klep.homekitty#16]
(make sure you also edit the title)

### Type (brand/model) of device
POPP Flow Stop 2

### Is it supported by HomeyKit?
Yes

### Device Classes
(find the device [here](https://tools.developer.homey.app/tools/devices) and post its class and virtual class, if it has one)

* _Class_: homealarm
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* onoff, Slått på, boolean
* ...
* ...

**Comment by robertklep** [comment]
I sometimes wonder how app developers come up with the class they pick for their devices 🤔

Anyway, it should be supported in the next test release.
