### ISSUE TITLE
Unable to delete devices 

### ISSUE THREAD

**Issue by marko0703** [robertklep/name.klep.homekitty#17]
Hi there,

I‘m not able to delete devices. It‘s coming every time a pop up saying „API request failed: unable to delete device“ In general I like the new app! Donation on the way ;-)

Thank you!
Marko

**Comment by robertklep** [comment]
Can you create a diagnostic report?

**Comment by marko0703** [comment]
7079f5f8-2768-4105-bd31-681e95bb92cbVon meinem iPad gesendetAm 16.12.2022 um 09:09 schrieb Robert Klep ***@***.***>:﻿
Can you create a diagnostic report?

**Comment by robertklep** [comment]
I don't see any delete actions being performed in the log, which can only mean that HomeKitty is unable to find the device that you're trying to delete. Which device(s) are you trying to delete?

**Comment by marko0703** [comment]
Can you please check again. I have tried now to delete several devices: - Haustür- IR Licht DoorBird- eufyCam Flur KG Ein/Aus-etc.Report: 28def284-fce8-474c-9e3f-b3f087c1add5Von meinem iPad gesendetAm 16.12.2022 um 09:16 schrieb Robert Klep ***@***.***>:﻿
I don't see any delete actions being performed in the log, which can only mean that HomeKitty is unable to find the device that you're trying to delete. Which device(s) are you trying to delete?

**Comment by robertklep** [comment]
The only device I can find in the logfile is "Haustür" (a contact alarm), so very strange.

Have you deleted those devices from Homey too?

**Comment by marko0703** [comment]
No, they are not deleted from Homey. All those devices are shown in Added but are not visible in HomeKit. I only could delete the Sonos devices. Everything else is coming with the message. The Haustür you have mentioned and I have tried to delete is a Nuki Lock. It‘s as well listed in Added but not visible in HomeKit.Von meinem iPad gesendetAm 16.12.2022 um 09:27 schrieb Robert Klep ***@***.***>:﻿
The only device I can find in the logfile is "Haustür" (a contact alarm), so very strange.
Have you deleted those devices from Homey too?

**Comment by robertklep** [comment]
Have you tried restarting HomeKitty?

**Comment by marko0703** [comment]
Now I have restarted. Some of the missing device are now in HomeKit but still not able to delete devices. Tried again to delete 2 ones. Report: c16b6b7d-5a38-4022-a4eb-b2f841843149Von meinem iPad gesendetAm 16.12.2022 um 09:32 schrieb Robert Klep ***@***.***>:﻿
Have you tried restarting HomeKitty?

**Comment by marko0703** [comment]
Thanks Robert!Yes, in the previous App I did it like that that I have deleted the ones I don‘t need in HomeKit to consider the max 150. But as I couldn‘t delete the ones which even were not in HomeKit yet I was wondering why I can‘t delete those.Von meinem iPad gesendetAm 16.12.2022 um 09:45 schrieb Robert Klep ***@***.***>:﻿
Ah right, I see the issue now:
[log] 2022-12-16 08:36:41 [HomeKitty] [eufyCam Einfahrt:XXX] reached the HomeKit limit of how many devices can be bridged

The HomeKit protocol only supports a maximum of 150 devices, and you have more.
However, HomeKitty doesn't take into account that some devices couldn't be added because of that limit, and it will still show them in the list of devices in the settings. I'll have to fix that.
In the mean time, I'll e-mail you the diagnostic report so you can see which devices were, and which weren't, added. That way, you can remove devices that were added but don't have to be, to make room for devices that couldn't be added but should. Once you removed the devices you don't need, you have to restart HomeKitty again.
I will look into fixing the issue.

**Comment by robertklep** [comment]
Deleting a device does two things: it will remove the device from HomeKit, and it will remember that the device shouldn't be added to HomeKit in the future. But in this case, your devices weren't added to HomeKit to begin with, so they couldn't be deleted from it.

I will change the settings page so it will keep track of how many devices are already added, and just refuse to add more if it has reached the limit. And it should also allow devices to be "deleted" if they aren't really added to HomeKit due to that limit, so you can still delete from to make room.

**Comment by robertklep** [comment]
This should be fixed (or at least improved) in the current test version: [v1.2.0](https://homey.app/a/name.klep.homekitty/test/)
