### ISSUE TITLE
Nest Protect not supported

### ISSUE THREAD

**Issue by basvdploeg** [robertklep/name.klep.homekitty#2]
Unfortunately the Nest Protect isn’t showing as a compatible device anymore. In HomeyKit they worked fine.

**Comment by robertklep** [comment]
If a device isn't showing up, find it here: https://tools.developer.homey.app/tools/devices

Then post the device's class, virtual class and its capabilities here.

**Comment by basvdploeg** [comment]
![2CC7764A-59B0-420B-94C9-E423C00DE21E](https://user-images.githubusercontent.com/4628469/205676203-28919165-bbb1-4eb8-9a81-8c3b8c40707c.jpeg)

**Comment by robertklep** [comment]
Thanks, will take a look ASAP.

**Comment by basvdploeg** [comment]
Thank you, Robert! I don’t want make a separate issue for this, but my weather station has the same problem. It showed things like temperature and humidity with HomeyKit, but can’t be used in HomeKitty.

Maybe you’ll be able to fix that one too.

![CCBE509B-6540-4E5F-B102-02D27CFD10EF](https://user-images.githubusercontent.com/4628469/205677251-5264fc98-8092-451e-976b-4546339d4303.jpeg)
![00E478ED-3297-463D-93BD-71E18C53AD03](https://user-images.githubusercontent.com/4628469/205677261-b3530e5a-0701-4be9-8260-3f3d3d5174db.jpeg)

**Comment by basvdploeg** [comment]
> It's actually easier for me if you created a separate issue for it 😅

Sorry 😅 Opened a new one: #3

**Comment by robertklep** [comment]
Do you know how to run and install apps from the command line? I just pushed a rather large update that requires some testing before I push it to the app store, and I'm interested to know if your issues are fixed by it (and that it doesn't introduce any additional issues).

**Comment by basvdploeg** [comment]
Yes! I’ll try it as soon as I’m home again. Thanks for your hard work!

**Comment by basvdploeg** [comment]
v1.0.5 fixed this! ✅
