### ISSUE TITLE
Error when adding device

### ISSUE THREAD

**Issue by raymondwigmore** [robertklep/name.klep.homekitty#20]
![image](https://user-images.githubusercontent.com/43473117/208413918-9d844843-deae-44eb-b6a5-2558c37bd3b0.png)

Running HomeKitty v1.2.1
Homey 8.1.0

also appeared under v1.2.0, but didn't have time to log

**Comment by robertklep** [comment]
That's not an error from my app 🤔 When does it appear?

**Comment by raymondwigmore** [comment]
When I try to add a device in HomeKitty. Aka switch HomeKitty on at a device.

PS love your new features/functionalities

**Comment by raymondwigmore** [comment]
Already dit a restart and full switch on/off of HomeKitty, keeps happening... not with excluding a device, but including it again (even same device that did exclude) shows this error...

Shall I try a full homey reboot for you?

**Comment by robertklep** [comment]
Hmm I'm also getting an error now when trying to turn on a device (different error than yours, but still an error). It only happens in the mobile app, not on the [website](https://tools.developer.homey.app/tools/app-settings).

**Comment by raymondwigmore** [comment]
I'm running Homey TestFlight 6.11.9 (1024)

**Comment by robertklep** [comment]
I'm not 😅

I'll has to ask on Slack what the reason might be for this.

**Comment by robertklep** [comment]
Found the issue, will push an updated test version shortly.

**Comment by robertklep** [comment]
Try v1.2.2: https://homey.app/a/name.klep.homekitty/test/

**Comment by raymondwigmore** [comment]
Perfect! Solved! Thank you
