### ISSUE TITLE
Roller Shutter dont´work properly with version 1.22

### ISSUE THREAD

**Issue by Dici71** [robertklep/name.klep.homekitty#21]
Hi,

i tested the new version 1.22 yesterday. but I got problems with my Philio Roller Shutters. when I want to close them they went down a few percent and went up again automatically. so I went back to version 1.10 which works properly for me.

**Comment by robertklep** [comment]
Try v1.2.3

**Comment by robertklep** [comment]
Ah no, v1.2.3 likely won't work either. Expect v1.2.4 to appear soon.

**Comment by Dici71** [comment]
ok....i´ll wait...

**Comment by robertklep** [comment]
Just pushed v1.2.4, it's now the current test.

**Comment by Dici71** [comment]
it works now....thanks !

**Comment by robertklep** [comment]
Ah good! Thanks for the feedback 👍🏻
