### ISSUE TITLE
Icon (CSS?) issue in app settings

### ISSUE THREAD

**Issue by basvdploeg** [robertklep/name.klep.homekitty#22]
Wide device icons do not scale properly in the apps settings list. 

Probably because only their height is set in CSS.

![IMG_2157](https://user-images.githubusercontent.com/4628469/208689216-51688a57-96e0-4086-9366-3163494b5df8.PNG)

**Comment by robertklep** [comment]
It also has `object-fit: contain` but I guess that's not supported.

Can you try the current Github version? I don't have any apps that have large icons so can't really test easily myself.

**Comment by basvdploeg** [comment]
Thanks! That fixed it. ✅

**Comment by robertklep** [comment]
Thanks for testing! Will push it as test release soon.
