### ISSUE TITLE
Support additional Dufy Security App Devices passthrough HomeKitty

### ISSUE THREAD

**Issue by DolmensDude** [robertklep/name.klep.homekitty#23]
(make sure you also edit the title)

### Type (brand/model) of device
Eufy Doorbell
Eufy Floodlight Cam 2 Pro

### Is it supported by HomeyKit?
No (not currently)

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

doorbell
Driver | homey:app:com.eufylife.security — driver_VIDEO_DOORBELL_2K_BATTERY

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

(let me know if I should capture these better!)

for doorbell

onoff
CMD_DEV_LED_SWITCH
alarm_motion
measure_battery
measure_temperature
CMD_DOORBELL_QUICK_RESPONSE
CMD_START_STREAM
CMD_SET_SNOOZE_MODE_HOMEBASE
CMD_IRCUT_SWITCH
CMD_BAT_DOORBELL_VIDEO_QUALITY
CMD_BAT_DOORBELL_WDR_SWITCH
NTFY_MOTION_DETECTION
NTFY_FACE_DETECTION
NTFY_PRESS_DOORBELL

for floodlight cam 2 pro

onoff
CMD_DEV_LED_SWITCH
alarm_motion
CMD_IRCUT_SWITCH
CMD_SET_FLOODLIGHT_MANUAL_SWITCH
CMD_INDOOR_PAN_TURN
CMD_SET_ARMING
CMD_SET_ARMING_HUB
CMD_REBOOT_HUB
CMD_START_STREAM
CMD_SET_SNOOZE_MODE
CMD_TRIGGER_ALARM
CMD_SET_HUB_ALARM_CLOSE
NTFY_MOTION_DETECTION
NTFY_FACE_DETECTION
NTFY_PET_DETECTED

**Comment by DolmensDude** [comment]
eufy HomeBase2 is also not supported, although motion sensors linked to the homebase2 are coming through.

class is homealarm

**Comment by robertklep** [comment]
@martijnpoppen how is the `onoff` capability used for the doorbell? Is that the capability that's used to signal the doorbell has been pressed? And if so, does it switch on and then automatically back to off after some time?

**Comment by DolmensDude** [comment]
Hopefully these tables’ formatting doesn’t get mangled by replying via mail ;-)

onoff
Turned on
boolean
null
truefalse

SET

UNSET

CMD_DEV_LED_SWITCH
Status LED
boolean
null


alarm_motion
Motion alarm
boolean
false

3 hours ago
measure_battery
Battery
number
91

14 hours ago
measure_temperature
Temperature
number
13

14 hours ago
CMD_DOORBELL_QUICK_RESPONSE
Send Quick Response
enum
null
123456

SET

UNSET

CMD_START_STREAM
Stream url
string
null


CMD_SET_SNOOZE_MODE_HOMEBASE
Set Homebase snooze mode
string
null


CMD_IRCUT_SWITCH
Toggle IR
string
null


CMD_BAT_DOORBELL_VIDEO_QUALITY
Toggle HDR
string
null


CMD_BAT_DOORBELL_WDR_SWITCH
Toggle WDR switch
string
null


NTFY_MOTION_DETECTION
Motion Detected
boolean
false
truefalse

SET

UNSET
3 hours ago
NTFY_FACE_DETECTION
Person Detected
boolean
false
truefalse

SET

UNSET
14 hours ago
NTFY_PRESS_DOORBELL
Doorbell Press Detected
boolean
false
truefalse

SET

UNSET
14 hours ag
o


ID
Title
Type
Value
Set Value
Last Changed
onoff
Turned on
boolean
true
truefalse

SET

UNSET
21 hours ago
CMD_DEV_LED_SWITCH
Status LED
boolean
null


alarm_motion
Motion alarm
boolean
false

21 hours ago
CMD_IRCUT_SWITCH
Toggle IR
string
null


CMD_SET_FLOODLIGHT_MANUAL_SWITCH
Light
boolean
false
truefalse

SET

UNSET
21 hours ago
CMD_INDOOR_PAN_TURN
CMD_INDOOR_PAN_TURN
boolean
null


CMD_SET_ARMING
Arm Mode
enum
null
homeawayschedulegeodisarmedoffcustom_1custom_2custom_3

SET

UNSET

CMD_SET_ARMING_HUB
CMD_SET_ARMING_HUB
boolean
null


CMD_REBOOT_HUB
Reboot
string
null


CMD_START_STREAM
Stream url
string
null


CMD_SET_SNOOZE_MODE
Set snooze mode
string
null


CMD_TRIGGER_ALARM
Turn generic alarm on
string
null


CMD_SET_HUB_ALARM_CLOSE
Turn generic alarm off
string
null


NTFY_MOTION_DETECTION
Motion Detected
boolean
false
truefalse

SET

UNSET
21 hours ago
NTFY_FACE_DETECTION
Person Detected
boolean
false
truefalse

SET

UNSET
21 hours ago
NTFY_PET_DETECTED
Pet Detected
boolean
false
truefalse

SET

UNSET
21 hours ago

**Comment by DolmensDude** [comment]
ugh... table formatting got "flattened"... :-(

**Comment by robertklep** [comment]
@DolmensDude not a big issue, I only really need the capability names and I can see those in the text 😊 I think the only thing missing is the device class for the floodlight cam 2 pro

**Comment by DolmensDude** [comment]
For the floodlight camera 2 pro, this is the class

Class	camera

**Comment by DolmensDude** [comment]
How are devices split up into subclasses/capabilities?

The floodlight 2 pro cam is actually, an alarm, a light, a multitude of sensors/states, and also a camera….

**Comment by robertklep** [comment]
@DolmensDude given that its class is `camera` I probably won't be able to meaningfully "translate" it to a HomeKit device at all.

**Comment by robertklep** [comment]
So from what I can see:
* it should be able to support the doorbell if @martijnpoppen can explain how it handles `onoff`
* it should _already_ support the Homebase2 alarm system because there's already generic support for device class `homealarm` and capability `onoff`. @DolmensDude how are you concluding it's not supported?
* the Floodlight device can't be supported

**Comment by DolmensDude** [comment]
HomeKitty Devices page



The Homebase2 is listed, but the slider cannot be slid to ON position.



When I choose “unsupported” view, it’s in that list of items, alongside the doorbells, a Eufy Robovac and two pet doors :-)

**Comment by robertklep** [comment]
@DolmensDude what happens with the HomeKit slider if you press the on/off button in Homey?

**Comment by DolmensDude** [comment]
I cannot move the slider in this overview.

If I go back to the devices page, touching this device here does not turn it off/dim it like with other devices.  It’s just on.

**Comment by DolmensDude** [comment]
Yep, probably.

At least it’s a mismatch between the two. 

I was late to the game for Homey, already in the HomeKit space, but bridging stuff into HomeKit was a great idea. A bit oversold by Homey that they had HomeKit support, so have been using the predecessor HomeyKitty off and on over the last year.

Homebridge requires maintenance that Homey tries to do on its own as it’s more productized.  

For eufy, Martijn seems more timely with taking care of issues, although Homey cannot do ffmpeg transforms, so video handling is out of the question.  The Homebridge eufy solution has fallen over twice recently - so I am looking at what can actually work on Homey, and what, if any, required functionality can and should be left to the native eufy app… or ultimately just ripping eufy out of the solution (which is a big deal actually).

We’ll see…. But what you guys do is truly fantastic. Truly!

**Comment by martijnpoppen** [comment]
The on/off might be related to the device settings. Every device has a checkbox in the settings if you want to have it permanently on. 
Because turning off camera's is not really a standard feature :p 

Default it's just a on/off. but you can set it to always on

**Comment by martijnpoppen** [comment]
Not familliar with HKSV. But it's possible to trigger a HLS or RTMP stream from Homey. Not sure if that would work inside Homekit?

**Comment by robertklep** [comment]
I've never done anything with HKSV either but I briefly glanced at the HomeBridge implementation for Eufy and it looks like it requires a bunch of stream metadata.

**Comment by martijnpoppen** [comment]
Ah yes I see, and it needs FFMPEG to convert the data to a actual stream

**Comment by robertklep** [comment]
Okay, so Apple is making life more difficult than it should: there's a HomeKit service called "Doorbell" which I assumed I could use, but it doesn't work:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/1190916/209155813-367f20c3-5c70-4c43-8f43-624f9c010e12.png">

It looks like standalone doorbells aren't supported (anymore) and they should be part of a "video doorbell" accessory. HomeKitty at the moment doesn't support setting the accessory category, and I don't know if it will work if I use the correct category but without the "video" part (which I can't support). So this may take some time.

**Comment by DolmensDude** [comment]
ah yes, the proverbial “when’s a doorbell not really a doorbell?” dilemna!

Another day, it’s almost Christmas!

**Comment by martijnpoppen** [comment]
Really nice! :D

**Comment by robertklep** [comment]
I haven't implemented any other capabilities for the doorbells yet besides the button-pressed one. And the reason that they don't show up is very likely because of what I said, namely that they aren't supported by the iOS Home app (this is just Apple being stupid: the doorbell devices are actually supported by the protocol, it's just that the Home app itself cannot handle them).

As for the HomeBase2, I don't know why it's not working, and without an actual device I can't really debug that issue either 😬

**Comment by DolmensDude** [comment]
I have the Home app on macOS, tvOS, iPadOS as well… iPadOS being the “full” version like the iOS version. 

There’s no hurry to do this right now. I cannot remove the HomeBase2 but perhaps I share to you for a debug session at some point down the line. 

I’m still truly happy that the motion sensors are working!!! These were truly important!
