### ISSUE TITLE
Somfy RTS blinds: strange behavior

### ISSUE THREAD

**Issue by petomei** [robertklep/name.klep.homekitty#26]
I noticed a strange behavior with my Somfy RTS blinds, which are integrated via the official Somfy app:
Under HomeyKit, the operation worked as expected:
[Homey-App] ∧ = Up, ◎ = My-Position, ∨ = Down
[Home-App] Top = Up, Middle = My-Position, Bottom = Down.
After I switched to HomeKitty, the blinds reappeared in HomeKit but their operation had changed, both in the Homey app and in the Home-App:
∧ = Up, ◎ = very short movement of the blind, ∨ = Down (Homey app)
Top = Up, Middle = very short movement of the blind, Bottom = Down (Home app).
And: Some blinds moved randomly (open, My or close) only by opening the Home App or without any interaction.

I solved the problem for now by removing the blinds from HomeKitty again and reactivating HomeyKit for this purpose.

**Comment by robertklep** [comment]
I've had some issues with implementing support for this device, so it could well be that it doesn't work properly (but it's very difficult for me to debug since I don't have any of these devices myself).

**Comment by robertklep** [comment]
Check out this comment: https://github.com/robertklep/name.klep.homekitty/issues/18#issuecomment-1364664654
