### ISSUE TITLE
Thermostat measured temperature not being passed through to HomeKit correctly

### ISSUE THREAD

**Issue by jmdraper** [robertklep/name.klep.homekitty#28]
Weird problem since moving from HomeyKit to HomeKitty - I have a Secure Meters Z Wave thermostat which I publish using the app to HomeKit. Has worked well for years on HomeyKit. With HomeKitty, I notice the current measured temperature isn’t correctly passing through to HomeKit. The HomeKit device appears correctly as a thermostat and does appear to get some kind of updates since the displayed current temperature in HomeKit does  I think change from time to time, but it’s almost never the same as the value showing in Homey app for that device. I’ve not yet spotted any pattern in the difference between the two.

**Comment by robertklep** [comment]
If it's not too much of a hassle, can you see if [the current HomeyKit test version](https://homey.app/a/com.swttt.homekit/test/) has the same issue? I wonder if this is an issue with SDKv3.

**Comment by jmdraper** [comment]
Hi Robert. Thanks for looking into this. I installed the test version of HomeyKit, added the HomeyKit-published hub to HomeKit and then switched just that thermostat device over to the HomeyKit from HomeKitty for testing. Exactly the same behaviour there so maybe as you say something to do with SDKv3. Another possibility is I can't remember whether I upgraded to the new HomeKit architecture when that first landed on iOS 16.2. I have been using public beta versions of iOS so maybe I said yes to that if it was offered when the 16.2 beta first landed.

It looks like possibly the current temp is being rounded in some way? Though slightly oddly since currently in Homey it's showing 18.8C and in HomeKit as published by HomeyKit it's showing 18.5C. I'll keep an eye on it and see if I can spot a definite pattern.

**Comment by robertklep** [comment]
I haven't updated to the new architecture, and everything seems to work okay, but I don't use Homey for my actual home automation so I only test with virtual devices. So difficult to say what could be causing your issues.

As for the rounding: that's just very annoying behaviour in the iOS Home app 🤷🏼‍♂️ Even though "under the hood" the temperature is set correctly to 18.8, the app is showing 18.5. Alternative HomeKit apps, like [Home+](https://hochgatterer.me/home+/) which I usually use, show the actual temperature correctly (which means it's a choice that Apple made to only show rounded values).
