### ISSUE TITLE
"Cannot Bridge more than 149 Accessories"

### ISSUE THREAD

**Issue by snarstad** [robertklep/name.klep.homekitty#29]
I love this app and I can't even imagine the hard work you must've put into it. THANK YOU!!! ...but would it be possible to use more then 149 accessories? I'm at about 220 atm and there will be about 30 more added. I'm sure the answer is here somewhere but I'm too new to GitHub to find it. Cheers /Jonas

**Comment by robertklep** [comment]
The 149-devices limit is imposed by the HomeKit protocol.

I might find a way to work around it, but it wouldn't be trivial (it basically means setting up multiple "bridges").
