### ISSUE TITLE
HomeKitty doesn't work anymore

### ISSUE THREAD

**Issue by Dici71** [robertklep/name.klep.homekitty#31]
Hi,

seems that Homekitty doesn't work anymore....can you please check ?

Many thanks !

**Comment by robertklep** [comment]
You have to provide more info, it's working fine for me and I don't see any crash reports.

**Comment by Dici71** [comment]
1. all devices are unreachable via Home App....
2. in the homey app there's a message saying that home kitty doesn't work anymore

![IMG_0908](https://user-images.githubusercontent.com/90046346/212258627-09e316eb-d05d-472d-b7df-caa9737d3b3f.PNG)

**Comment by robertklep** [comment]
That's an internal Homey error that I cannot do anything about. I already reported this to Athom [months ago](https://github.com/athombv/homey-web-api-issues/issues/15) but they either cannot solve it, or they're not interested in doing so.
