### ISSUE TITLE
Problem with dimming lights

### ISSUE THREAD

**Issue by itzbolsi** [robertklep/name.klep.homekitty#35]
Hi, having some problems with dimming lights on the new app, worked fine with the old one.
Sometimes the first try/tries works fine but not always. After dimming once, it usually fails on the next try, jumps back to last dimming level without the lights changing. After this it dosent respond to new inputs.
(When dimming directly on homey everything works fine.)

Also, old Homeykit app is uninstalled and the integrated homey one is disabled so shouldent be any conflicts there.

### Type (brand/model) of device
Heatit Z-Dim (Heatit controls app)

### Is it supported by HomeyKit?
Yes, worked fine on Homeykit, but problems with Homeykitty.

### Device Classes
zw_device_class_basic	"BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic	"GENERIC_TYPE_SWITCH_MULTILEVEL"
zw_device_class_specific	"SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL"

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID	850de1fa-c3e7-4d17-bb4d-f0256bc31275
Name	Lys stue
Class	light

**Comment by robertklep** [comment]
Given that these are Z-Wave devices, this thread might be relevant: https://community.homey.app/t/z-wave-perormance-issues/75470

To rule out issues with HomeKitty, you could re-install HomeyKit (and pause HomeKitty) and see if it still works, but like I said on the forum, your issues are strange: it should either work, or not, but if it works only intermittently or sometimes, it's very likely not a HomeKitty issue and debugging might be difficult 🥴

**Comment by itzbolsi** [comment]
My Z-wave network is very stable. Like I mentioned in my original post, when dimming in Homey directly everthing works fine.So dont see the relevance in the link you posted 🤷🏼‍♂️ But I will try to uninstall homekitty and install homeykit again to see if works.

**Comment by itzbolsi** [comment]
Update, uninstalled Homekitty and installed Homeykit. Same light source as before is now stable and dims like you should expect. Tested dimming up and down several times. Could there be a bug in Homekitty?

**Comment by robertklep** [comment]
If it works with HomeyKit and not with HomeKitty it's certainly related to the latter, but I wouldn't necessarily call it a bug.

Can you find the device here: https://tools.developer.homey.app/tools/devices

And then make a screenshot of the list of capabilities. Here's an example of one of my lights:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1190916/214248892-268c2f23-fc79-440d-b41a-0e1a4131bcf6.png">

**Comment by itzbolsi** [comment]
Attached.
<img width="985" alt="Screenshot 2023-01-24 at 10 00 46" src="https://user-images.githubusercontent.com/61293370/214250340-f54c482a-3850-47b2-86c3-11766bcdaca3.png">

**Comment by robertklep** [comment]
Nothing out of the ordinary there.

Can you restart HomeKitty, wait until it's fully started (and working in iOS), switch/dim the device a couple of times, and then create a diagnostics report (from the mobile app).

Hopefully I'll be able to find out why it's doing what it's doing.

**Comment by itzbolsi** [comment]
Done, reference: 007de8f7-a39f-459c-a721-e4966efdd7ef

It actually worked about 10 times now before it stopped responding and the dim level just kept jumping back.

**Comment by robertklep** [comment]
I think I found the reason why it's not working: your device is updating very often, 3 to 4 times a second sometimes:
```
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.53
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 53
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.49
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 49
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.48
[log] 2023-01-24 09:29:28 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 48
...
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.1
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 10
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.07
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 7.000000000000001
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.06
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 6
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] capability update - capability=dim raw=0.17
[log] 2023-01-24 09:29:44 [HomeKitty] [Lys stue] - update characteristic - name = Brightness value = 17
```

This is one thing that's different between HomeyKit and HomeKitty: HomeyKit will limit the number of updates to once per 500ms (so twice a second), and HomeKitty doesn't.

My guess is that this is causing the problem. I'll see if I can implement the same limiting in HomeKitty.

**Comment by robertklep** [comment]
Can you try the current test version? https://homey.app/a/name.klep.homekitty/test/

**Comment by itzbolsi** [comment]
Seems like that solved it. Fantastic 🤩

**Comment by robertklep** [comment]
Thanks for testing 👍🏻 I'll keep it as test version for a little while to rule out issues that others may have with the change, but if no one complains I will upgrade it to live/stable.

**Comment by itzbolsi** [comment]
@robertklep will this go in prod soon?

**Comment by robertklep** [comment]
Probably around the same time HP2023's firmware is released as stable, there are still changes being made that might impact HomeKitty.
