### ISSUE TITLE
Apple’s Home app fires the command 3 times

### ISSUE THREAD

**Issue by MichielTi** [robertklep/name.klep.homekitty#36]
Hi Robert, thanks for making this new app! I liked the previous app and I am confident that it will work even better.

But right now I have a problem:
I use it to send commands to my kids through Sonos. The strange thing is that these commands fire 3 times when I press the button in Apple’s Home app. But when I press the button in Homey, the command only fires once, like it should. I have tried several things like resetting the app but it still happens.

To make it very clear to me, I tested this with a new button and a flow that adds a line to the timeline in Homey. When I press the button in Homey, I get one line. When I press the button in Apple’s Home app, I get three lines…

Do you recognize this? Do you have any suggestions to solve this?

How did I test this:

I've created a virtual button 'Test':
<img width="395" alt="image" src="https://user-images.githubusercontent.com/123649184/214864415-01ba5197-bcfd-4918-8650-71e41577f019.png">

I made a test flow:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/123649184/214864725-90a8ffd7-934c-4913-b0a0-5a2c9b4ea061.png">

I've tested this via the Home app:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/123649184/214865056-20029931-e3b5-4052-9fa4-1e254956b94c.png">

And then I get 3 lines in the Homey timeline:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/123649184/214865504-c61ec814-1e49-4695-8729-cf2cc60e98d5.png">

**Comment by robertklep** [comment]
There was indeed an implementation issue with this button, but it will still always generate _two_ notifications due to the way buttons are implemented in Homey.

If you want to trigger Homey flows from HomeKit, you should use the Flow Starter device that HomeKitty provides (you can add it as a new device). This will make sure that a flow is only triggers once.

**Comment by MichielTi** [comment]
Thanks, the Flow Starter does the job!
