### ISSUE TITLE
[Ios 16.3 update and noting works anymore]

### ISSUE THREAD

**Issue by djdirty60** [robertklep/name.klep.homekitty#37]
Good day,

Had an update to iOS 16.3 today and are no longer connected to homey. Last night he did it...

Can you maybe look at it?

Thanks in advance
![13A829D2-DC55-44E5-BDB2-676EB0724F34](https://user-images.githubusercontent.com/13561831/214920787-799f8648-87c5-49e3-9c40-cbfc1d0eba8d.png)

**Comment by robertklep** [comment]
I've been on 16.3 since a few days and everything works fine for me 🤷🏼‍♂️

**Comment by djdirty60** [comment]
> I've been on 16.3 since a few days and everything works fine for me 🤷🏼‍♂️ Try restarting HomeKitty or your Homey.

I've already done that, and also reinstalled on HomeKit doesn't keep getting a response

**Comment by robertklep** [comment]
What do you mean by "reinstalled on HomeKit"?

FWIW, you can restart HomeKitty, wait a minute or so (so it's up and running), then send me a diagnostics report. But I'm fairly certain the issue isn't with the app 🥴

**Comment by djdirty60** [comment]
> What do you mean by "reinstalled on HomeKit"?
> 
> FWIW, you can restart HomeKitty, wait a minute or so (so it's up and running), then send me a diagnostics report. But I'm fairly certain the issue isn't with the app 🥴

Mean relinked in HomeKit.

90eb80f0-8e9a-47e1-913c-bc5cef423d9f

**Comment by robertklep** [comment]
Given that you could add HomeKitty back to HomeKit again means that the app is running okay.

Your issues might be related to a misbehaving and/or out-of-date Home Hub, like an Apple TV or HomePod. Do you have any?

**Comment by djdirty60** [comment]
> Given that you could add HomeKitty back to HomeKit again means that the app is running okay.
> 
> Your issues might be related to a misbehaving and/or out-of-date Home Hub, like an Apple TV or HomePod. Do you have any?

Found the problem... it's the Apple TV! But it's the latest generation. But if it's out of the HomeKit, everything does it again.

**Comment by robertklep** [comment]
Yes, this happens 😢 I have no idea why (I don't have any Home hubs myself). Sometimes it helps just turning off the hub functionality on the hub device, and then turning it back on again.

**Comment by djdirty60** [comment]
> Yes, this happens 😢 I have no idea why (I don't have any Home hubs myself). Sometimes it helps just turning off the hub functionality on the hub device, and then turning it back on again.

This version does not have a hub function, it is the 4K wireless 2022 version. It can't be used all hub. But think maybe the problem is with iOS 16.3 of the TV version. I had no problems with that. But at least thanks for your time

**Comment by djdirty60** [comment]
Good day,

Now I don't get a response at all. And the hub is not among them
