### ISSUE TITLE
Mill Heat Panel Heater 3rd Gen Not showing Correct Status or Temperature

### ISSUE THREAD

**Issue by bjornand1** [robertklep/name.klep.homekitty#38]
Hi, really appreciating the creation of HomeKitty!

It seems all my devices work properly, except one:

I have four Mill Heat products, with various degree of success through HomeKitty:

- Smart plug, shows correct status and temperature, but making changes to the settings in Home does not change the actual state of the plug
- Panel Heater 2nd gen, same as above, shows correct status, but the status cannot be changed
- Panel Heater 3rd gen, does not even show the correct status or temperature (it says 100 degree C)

I realize these are probably not products that too many people have, but it would be nice to them working (they do not work in HomeyKit either).

**Comment by bjornand1** [comment]
Link to the 3rd gen: https://millnorway.com/product/mill-glass-wifi-panel-heater-400w/

**Comment by robertklep** [comment]
Luckily I don't need to have the actual devices to be able to add support for them to HomeKitty 😅

But your issues point to perhaps a misbehaving Home Hub (HomePod or Apple TV). If a device isn't supported at all, it just won't show up in Home. If a device is (partially) supported, this support should work both ways: from Home to Homey, and from Homey to Home. If one direction is working but the other isn't, the chance that this is caused by an issue in HomeKitty is _very_ small.

So if you have Home Hub devices, try disabling their Home Hub support and see if that solves the problem. Or reboot Homey and your iPhone/iPad to see if that solves the problem.

**Comment by robertklep** [comment]
Try restarting HomeKitty, wait a few minutes, then try changing the iOS/Home state for a device that isn't working, and create a diagnostics report (please let me know the name of the device that you tried, so I can find it in the report).

**Comment by bjornand1** [comment]
Thanks, tried this, but changing Desk Panel Heater from Heat to Off, wth no effect on the panel heater.

Code:
1e39ed6b-8b16-4660-8e1d-0922a855b941

**Comment by robertklep** [comment]
Thanks, I got the report. Like I thought, HomeKitty isn't receiving any events from Home; in other words, state changes in Home don't reach HomeKitty, and therefore cannot be passed to the Homey devices.

Also, the report also explains why the temperature isn't working:
```
[HomeKitty 6BDF@MB Panel Heater@MB Panel Heater@Current Temperature] characteristic was supplied illegal value: number 1223 exceeded maximum of 100
[HomeKitty 6BDF@MB Panel Heater@MB Panel Heater@Target Temperature] characteristic was supplied illegal value: number 5 exceeded minimum of 10
```

It's saying the temperature of your panel is 1223°C, which seems a bit high. Also, that capability is typically used to measure _ambient_ temperature, so the room temperature. And a target temperature of 5 also seems a bit low.

**Comment by bjornand1** [comment]
Well, then I know that much. Any ways that could be fixed? Is it something the developer of the Mill app must look into?

**Comment by bjornand1** [comment]
Well, the measured temperature is not correct!! But the set temperature, at 5 C, is in fact correct.

The problem is that the app developer has stopped updating the app.

**Comment by robertklep** [comment]
The measured temperature capability in Homey doesn't have a default min/max value. The target temperature does (4-35°C), so I'll check how easy it is to use the same values in HomeKit.

**Comment by bjornand1** [comment]
By the way, HomeKitty seems just as stable as HomeyKit, at least for the devices I have. Do you see any reasons for not going all in and removing HomeyKit at this stage?

**Comment by robertklep** [comment]
A lot of people donated for me to port HomeyKit to the new Homey Pro hardware, once that's done (my new Homey Pro _literally_ got lost in the mail...) I will publish a final stable version for HomeyKit and then ask Athom to hide HomeyKit from the store so HomeKitty will be the only visible HomeKit implementation for new users.

**Comment by bjornand1** [comment]
Great, I made a contribution as well, looking forward to the final version!

**Comment by robertklep** [comment]
Thanks for your donation! To be clear: the final version will be for HomeyKit, which I hope you're not using anymore 😁

**Comment by bjornand1** [comment]
Well, I am using HomeyKit right now, but am transitioning to HomeKitty. But after moving over to HomeKitty, I will not need to do anything else, even when you publish the new version(s)?

**Comment by robertklep** [comment]
That's correct. I will focus my development efforts on HomeKitty. Given the issues that are popping up with the new HP2023 hardware, I'm not even sure if the current version of HomeyKit will be compatible with the new hardware (even though Athom has suggested that all SDK3 apps will be supported). I _will_ make sure that HomeKitty is going to be compatible.

**Comment by bjornand1** [comment]
Sorry to keep bothering you about this, but this issue might impact the development of HomeKitty?

I have done some more experimenting:

- Purchased a Namron Zigbee heater, for which there is an official Homey app created by the Namron company. It works performanceectly in Homey. As with the Mill heaters, the Namron heater also is shown with the correct current and target temperature in HomeKit. However, the current off/heat/auto status is not correct and trying to change this in HomeKit does not trigger any change at the heater (but controlling it in Homey works as intended)
- I tried turning on the Homey experimental HomeKit function, and the Mill heaters and the Namron heater work (or more accurately do not work) the same way through that route

So I am starting to wonder whether there is something inherent in how Homey deals with heating devices that makes it hard or even impossible to expose them properly to HomeKit?

**Comment by robertklep** [comment]
The issue isn't related to heating devices but to Homey devices in general.

Homey doesn't have strict device type declarations (saying that a device of type "heater" should always have capability X for measured temperature, capability Y for target temperature, and capability Z for the device state).

The HomeKit protocol, however, does have strict declarations, so HomeKitty is a best-effort implementation to try and translate _most_ Homey devices to HomeKit. This works for the most part, but not always.

Homey's experimental HomeKit implementation is a very minimal effort to do the same, only enough to be able to say that Homey supports HomeKit. But it doesn't support nearly as many devices as HomeKitty does.

If changing the device state only works one way (from Homey to HomeKit but not the other way around), there can be several reasons for this to occur. But without me having the actual device makes it almost impossible to determine the actual reason, though. At least in theory, it should work: I have a lot of virtual devices that implement different device types so I can test HomeKitty's implementation for them.

**Comment by bjornand1** [comment]
Thanks for the clarification, then I understand better the issues in play!

**Comment by bjornand1** [comment]
By the way, I mentioned HomeKitty several places on my smart home site: http://smarthjem.hbandersen.synology.me/?lang=en
