### ISSUE TITLE
KaKu Dimmer Socket adds multiple devices

### ISSUE THREAD

**Issue by basvdploeg** [robertklep/name.klep.homekitty#4]
When adding a Kaku Dimmer Socket, both a **lamp and socket** are included in HomeKit. Previously only the dimmer part (light) got added. Preferably only the dimmer controller should show up, without the separate extra socket device.

<img width="1362" alt="Scherm­afbeelding 2022-12-05 om 19 36 20" src="https://user-images.githubusercontent.com/4628469/205716413-82c9f2b5-ef3d-4934-8164-696dd0234cae.png">

**Comment by robertklep** [comment]
This happens because both the "class" and the "virtual class" match a (different) device type. I think that if a device type matches a virtual class it should not also try to match the regular class against other device types.

**Comment by basvdploeg** [comment]
This is the same type KaKu dimmer socket, but without the virtual light class. That one ignores the dimmer completely and only shows an on/off switch in HomeKit. 

<img width="1370" alt="Scherm­afbeelding 2022-12-05 om 20 22 26" src="https://user-images.githubusercontent.com/4628469/205724882-6bdf2c19-86c6-4ed0-abc3-0c503c5e2a55.png">

**Comment by robertklep** [comment]
Does this device show up as a dimmable socket when you use HomeyKit? Because "dimmable sockets" isn't something that HomeKit itself supports.

**Comment by basvdploeg** [comment]
v1.0.5 fixed this! ✅
