### ISSUE TITLE
homekit is not responding

### ISSUE THREAD

**Issue by effe-7** [robertklep/name.klep.homekitty#40]
I have already canceled the bridge several times and reconnected in the Apple Home application.  but then after a few days it doesn't work anymore all the devices are in "not responding" state and Homey too then goes into this state.  I tried uninstalling and reinstalling the HomeKitty app.  in two years of the previous version I never had this problem.

**Comment by robertklep** [comment]
What do you mean by "and Homey too then goes into this state"? It sounds like a Homey issue to me, to be honest.

**Comment by effe-7** [comment]
I mean that the connection with Homey hub is in "not responding" state

**Comment by effe-7** [comment]
the devices in Homey all work correctly and from an apple device the Flow commands work correctly

**Comment by effe-7** [comment]
only in the Apple Home application do all the devices stop being connected… among the many tests I also tried to restart Homey.![image](https://user-images.githubusercontent.com/83612865/218084137-5f66d17e-b9a1-4c4f-b0eb-9fc63a365e80.png)

**Comment by robertklep** [comment]
And what does "and from an apple device the Flow commands work correctly" mean?

**Comment by effe-7** [comment]
tramite la funzione Comandi di apple posso comandare dei Flow preferiti in Homey.  ed anche da widget Homey comando i Flow

**Comment by effe-7** [comment]
Using the Apple Commands function, I can command my favorite Flows in Homey.  and also from the Homey widget I command the Flow

**Comment by effe-7** [comment]
congratulations for the response times

**Comment by robertklep** [comment]
Thanks for the clarification 😊

All I can say that provided that the HomeKitty app is running (and not crashing), "Not Responding" errors are almost certainly not caused by HomeKitty, but by something else. One very common cause is a misbehaving Home hub (like an Apple TV or Homepod) that is causing issues.

**Comment by tomkieboy** [comment]
Hello,
I also have the same problem.
Nothing from homekitty bridge is responding in apple homekit.
Already reset homey, homepods, homekitty app.

**Comment by robertklep** [comment]
@tomkieboy I still can't do anything about it, I'm afraid.

**Comment by tomkieboy** [comment]
Is it a common issue? 
So its waiting for an update from apple side?

**Comment by robertklep** [comment]
It's not a common issue, HomeKitty and its predecessor HomeyKit have a combined 10.000 installs and this issue happens to _some_ users.

Sometimes it works to (temporarily) disable the Home Hub functionality of the (in your case) Homepods completely. Another possible reason is when Homey is placed in a separate "IoT" VLAN that's not configured properly. Other times, the Homey of the user simply isn't stable, or is too busy (too many apps, or misbehaving apps).

**Comment by tomkieboy** [comment]
How do I disable the homepods hub function?

**Comment by robertklep** [comment]
I don't have a Homepod so not sure if it's even possible 😬 For other devices, it's in Settings > Home

**Comment by blutch32** [comment]
Hello, I am having the same issue with my Apple TV. I figured out that this issue often happened after the homeykit app get an update. Did you find a way to reconnect your devices on another way than adding them from scratch again ? Many thanks to the dev for this app btw :)

**Comment by robertklep** [comment]
@blutch32 try disabling then reenabling the Homekit Hub functionality of your Apple TV (if that's possible). Or restart the ATV.

**Comment by blutch32** [comment]
Thank a lot for the very fast answer ! Did tried it, but then figured out that homey was offline. It was still able to work during my first test but then was offline. Anyway, problem solve and your app is great ! My garage door are detected as store fyi but they are working anyway.
