### ISSUE TITLE
Unsupported Roborock S5 MAX

### ISSUE THREAD

**Issue by Domcuss** [robertklep/name.klep.homekitty#41]
Hello, is there any chance to get roborock in Homekit?
### Type (brand/model) of device
Roborock S5 MAX

### Is it supported by HomeyKit?
No

### Device Classes

What are it's class, and virtual class (if it has one)?

* _Class_: vacuumcleaner
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...ID: onoff, vacuumcleaner_state, measure_battery
* ...Title: Turned on, Vacuum cleaner state, Battery
* ...Type: boolean, enum, number

Thank you

**Comment by robertklep** [comment]
Looks like it should be relatively easy to support the basics for this device, but it may take some time to implement since I'm working on getting HomeKitty properly working on the new Homey Pro hardware.

**Comment by Domcuss** [comment]
Ok, thank you for your answer.

**Comment by robertklep** [comment]
Support (only "on/off", since HomeKit doesn't have a specific "vacuum cleaner" device type) has been added, but it may take some time before it reaches the test phase since it's part of the "new Homey Pro" update.

**Comment by robertklep** [comment]
The current test version should support this device now.

**Comment by mkormendy** [comment]
I have tried to use this and it shows my Roborock S5 as unsupported and won't switch. ![image](https://user-images.githubusercontent.com/1437667/230269060-f64fcdb0-0352-4dba-8e98-1e164e10057f.png)

**Comment by Domcuss** [comment]
Hello,
I still don't see the vacuum cleaner.
Is there somewhere to enable the test version?

Thank you

**Comment by robertklep** [comment]
The test version can be installed through here: https://homey.app/a/name.klep.homekitty/test/

**Comment by Domcuss** [comment]
Thank you, it works! Vacuum celaner is in homekit.
