### ISSUE TITLE
device selection

### ISSUE THREAD

**Issue by laustS** [robertklep/name.klep.homekitty#42]
Hello Robert
Thanks for all the work.
I have just uninstalled the “old” Homeykit and installed Homeykitty.
I like the obvious good ideas you have worked with.
I have run into a small issue that I have had to work around:
The configuration of which devices to reveal to Homekit (obviously you have some good thoughts on the interface in that area).
I can however not make it work as I’d expect.
After I select which devices to pass over, nothing happens in Homekit - is there a button to push that I have not found?
Anyway I then pushed the “Publish All Devices” … with the expected result. I have a room for all the unwanted doublets now, as I had with Homekit).

### Homey Pro (2017)
Apple Tv 
Operated on an Ipad Pro.

**Comment by robertklep** [comment]
If you enable/disable a device from the settings, it can take some time before that state is shown in the Home app, sometimes even requiring the Home app to be restarted before the device is shown/removed.

This is basically a shortcoming in Apple's own app, other HomeKit apps like Home+ are typically _much_ faster in adding or removing a device.

**Comment by laustS** [comment]
Thanks RobertI restarted Homekit - we have quite a few IOS devices and shut them all down - then rebooted the AppleTv (where the main Homekit app runs).That worked! Now exchange between Homey, via Homekitten, and Homekit works really good.Now I'll commence with some of the more advanced devices :-)Thanks!Laust Søndergaard Den 27. feb. 2023 kl. 19.05 skrev Robert Klep ***@***.***>:﻿
If you enable/disable a device from the settings, it can take some time before that state is shown in the Home app, sometimes even requiring the Home app to be restarted before the device is shown/removed.
This is basically a shortcoming in Apple's own app, other HomeKit apps like Home+ are typically much faster in adding or removing a device.

**Comment by robertklep** [comment]
Ah yes, a misbehaving Home hub (like your AppleTV) is also a common problem 😢
