### ISSUE TITLE
HomeKitty1 stopped working [Feature Request/Unsupported]

### ISSUE THREAD

**Issue by Julusmoen** [robertklep/name.klep.homekitty#43]
Homey pro 2019 crash log.
![IMG_6221](https://user-images.githubusercontent.com/30026349/222982154-104942e4-7c90-4584-be24-2c4f36d0c244.png)

(make sure you also edit the title)

### Type (brand/model) of device
...

### Homey Model
- [ ] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...
* ...
* ...

**Comment by robertklep** [comment]
I can't help with this issue, I'm afraid. It happens somewhere in Homey's network stack, which is out of reach for app developers.
