### ISSUE TITLE
[Feature Request/Unsupported] Camera support

### ISSUE THREAD

**Issue by mbnn** [robertklep/name.klep.homekitty#45]
(make sure you also edit the title)

### Type (brand/model) of device
UniFi Protect (via plugin) camera and doorbell

### Homey Model
- [X] Homey Pro 2023

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: camera
* _Virtual Class_: none

### Device Capabilities

Thanks for this great app, everything seems to work pretty good :grinning: However, my UniFi Protect Camera’s (using the Homey Unifi protect plugin) are not available to select in Homekitty, can that be added please? :grinning: I used that before with my doorbell and such to homekit.

* ...
* ...
* ...
![typ e](https://user-images.githubusercontent.com/1856746/225617800-4560b5aa-5970-470e-b29a-1fa0a30b98f9.jpg)

**Comment by robertklep** [comment]
> I used that before with my doorbell and such to homekit.

Do you mean the device was added to HomeKit directly?

Also, what type of support are you expecting from HomeKitty? Please bear in mind that things like snapshots and streaming video aren't possible with Homey.

**Comment by mbnn** [comment]
With Homeykit it worked, you could see the cameras, doorbell notification worked and you could view the camera. No snapshots or anything else necessary 😀

**Comment by robertklep** [comment]
HomeyKit never had any camera support 😅 I think you added the camera's directly, which is still an option: https://community.ui.com/questions/UniFi-Protect-with-HomeKit-Setup-Guide/3c47cc46-560c-4fcc-9eaa-d159a16c77e0

**Comment by mbnn** [comment]
I never used homebridge, but i did get notifications of doorbell rings 😀

**Comment by robertklep** [comment]
Ah sorry, I thought that was an official post about HomeKit support.

The doorbell might have worked, but you didn't post any information for it? Only the camera.

**Comment by mbnn** [comment]
Im gonna use scrypted for that on the synology so you may close this ticket 😀
