### ISSUE TITLE
Problem dimming lights

### ISSUE THREAD

**Issue by bnotten** [robertklep/name.klep.homekitty#46]
A similar issue had been mentioned before, but the update has not solved it for me. While trying to dim a fibaro dimmer 2 light, the dimslider in homekit immediately jumps back to the original value. Dimming is therefore not possible. It works fine in the homey app.

**Comment by robertklep** [comment]
Can you post a list of capabilities [as explained here](https://github.com/robertklep/name.klep.homekitty/issues/35#issuecomment-1401571604)?

And also post a diagnostic report [as explained here](https://github.com/robertklep/name.klep.homekitty/issues/35#issuecomment-1401584874).

**Comment by bnotten** [comment]
<img width="913" alt="Scherm­afbeelding 2023-03-22 om 19 31 35" src="https://user-images.githubusercontent.com/119496600/227003519-a473d078-bf9a-4049-9621-7ed35e2e43c1.png">

**Comment by robertklep** [comment]
You're running the latest _stable_ version of HomeKitty (v1.3.2), but you need to be running the latest _test_ version (v2.0.1): https://homey.app/a/name.klep.homekitty/test/

**Comment by bnotten** [comment]
My bad, I saw another thread posted with this issue. But i had made the assumption the update was implemented in the stable version already. It works like a charm now. Will donate.

**Comment by robertklep** [comment]
Thanks!
