### ISSUE TITLE
Flows are triggered 3 times

### ISSUE THREAD

**Issue by markhartNL** [robertklep/name.klep.homekitty#47]
I am big fan of the Homekitty app. I do experience some strange behavior that is also mentioned by someone else. I use some flows that are triggered by a virtual button. When I start this flow from the Apple home app these flows fire 3 times when I press the button. But when I press the button in Homey, the command only fires once, like it should. I have tried several things like resetting the app but it still happens.

I also tested this with a new button and a flow that adds a line to the timeline in Homey. When I press the button in Homey, I get one line. When I press the button in Apple’s Home app, I get three lines.

Is there any known solution?

**Comment by robertklep** [comment]
If you're using the virtual button merely as a flow trigger, you should use HomeKitty's "Flow Starter" device:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1190916/229270775-68373eee-7627-4d3f-b938-ac30c80f60bc.png">

These should trigger flows just once.
