### ISSUE TITLE
Airquality not showing in HomeKit

### ISSUE THREAD

**Issue by jahnkenneth** [robertklep/name.klep.homekitty#48]
(make sure you also edit the title)

### Aqara TVOC sensor
...

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [Y] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: sensor
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

![IMG_2863](https://user-images.githubusercontent.com/28279147/230736640-07a07f84-8369-49f9-801a-4042b839feed.png)

**Comment by jahnkenneth** [comment]
![Uploading IMG_2864.png…]()

**Comment by jahnkenneth** [comment]
![IMG_2864](https://user-images.githubusercontent.com/28279147/230736717-3f29f5a3-60aa-4c03-9ade-21dedb39c1a2.png)

**Comment by robertklep** [comment]
What does/did this device show with HomeyKit? As far as I know, that app never supported air quality.

HomeyKit only supports air quality based on the CO2 sensor, which your device doesn't have. The capability that you're showing thats related to air quality (`measure_AirQualityLevel`) is not a regular Homey capability but a custom one for the particular app you use to support the device. HomeKitty doesn't support custom capabilities.
