### ISSUE TITLE
After update connection not woking anymore

### ISSUE THREAD

**Issue by martin82private** [robertklep/name.klep.homekitty#49]
After update to 10.0.0 rc88 it s not possible to get it working. Before i d it configured and it was working. I already tried to completly reset the app and removed the bridge in homekit but if i want to add it it will not be avalaible.

**Comment by robertklep** [comment]
Yes, rc88 introduced an issue in HomeKitty, looking at it now.

**Comment by martin82private** [comment]
021d47bc-0d98-4079-9e9a-0e5df2bc4413

Thanks for your quick feedback and support

**Comment by robertklep** [comment]
Should be fixed in the current test version: https://homey.app/a/name.klep.homekitty/test/

**Comment by martin82private** [comment]
Many thanks it s working again
