### ISSUE TITLE
Fibaro Roller Shutter don´t open

### ISSUE THREAD

**Issue by Effendi68** [robertklep/name.klep.homekitty#50]
I installed the Version 2.1.0 and added my Fibaro Roller Shutters 2 to Apple Home. From open to close they work well but i can´t oben them. By typing at the button to open in Apple Home nothing happens but the status changes to open. When I use the slider to open, i can slide to the maximum and they open but they open only to 80%. I tested it with two shutters. 
Tom

**Comment by Effendi68** [comment]
Homey has the same status as Apple Home

**Comment by robertklep** [comment]
That's a Fibaro/Homey issue, HomeKitty does not actually control the devices itself, it just tells Homey to set a particular state and Homey passes that to the Fibaro app.

**Comment by Effendi68** [comment]
> That's a Fibaro/Homey issue
I understand that. However, the control in homey works without errors and these problems only exist with HomeKit. That doesn't quite make sense to me.

**Comment by robertklep** [comment]
I agree, but if HomeKitty works for devices with firmware version X but not firmware version Y, there's nothing I can do in HomeKitty to fix that.
