### ISSUE TITLE
Fibaro Switch no longer responding in Apple Home

### ISSUE THREAD

**Issue by bjornand1** [robertklep/name.klep.homekitty#51]
After months of working well, today a Fibaro Walli Switch was moved to Default Room and no longer responds to Apple Home commands or shows correct state. 

Log code: 93b0371e-ba9d-4bf9-b1e5-7ff7680f325e

**Comment by robertklep** [comment]
Nothing has changed to HomeKitty, so this sounds like a random Homey issue I'm afraid. The diagnostics report doesn't show anything that points to a possible cause, either.

If you have Home hubs in your network (Apple TV or HomePod), try rebooting those.

Also, perhaps your Homey needs a [PTP](https://community.homey.app/t/how-to-ptp/17304).

**Comment by bjornand1** [comment]
Restart of HomePod Mini fixed it👍
