### ISSUE TITLE
Garage door recognize as a window blind

### ISSUE THREAD

**Issue by blutch32** [robertklep/name.klep.homekitty#52]
Hi and thank you for your great app. My garage doors are recognized as window blinds or store instead of garage door. Is there any way to make the HomeKit app recognize these as garage door ?

**Comment by robertklep** [comment]
Can you find the device here: https://tools.developer.homey.app/tools/devices

And then post:
* its Class
* its list of capabilities (ID of capabilities is enough)

**Comment by blutch32** [comment]
Hi, yes sure !
- Class | blinds
- ID of capabilities : 
  - my-position type Boolean : 
     - true
     - false
  - windowcoverings-state type enum : 
     - up
     - idle
     - down
  
![IMG_4334](https://github.com/robertklep/name.klep.homekitty/assets/128053615/25caade6-dd3e-4787-88f1-91224dace48e)

**Comment by robertklep** [comment]
The app is saying the device is a window covering of type "blinds", there's not much HomeKitty can do about that 🤷🏼‍♂️

**Comment by blutch32** [comment]
Does this naming comes from Apple ? On the developer tool, the name is as following : 
- controllableName	"io:DiscreteGarageOpenerWithPartialPositionIOComponent"

so basically the issue comes from Apple I guess ?

**Comment by robertklep** [comment]
No, the Homey app for your device sets the device class, which is "blinds".

HomeKitty has no idea of knowing that you're using it as a garagedoor opener.

**Comment by blutch32** [comment]
Oh, get it now. I juste changed this parameter from blind to garage door I didn’t even know it was existing… but then it is in the unsupported list of the homekitty app.

**Comment by robertklep** [comment]
HomeKitty only supports the `garagedoor_closed` capability for the `garagedoor` device class.

Both Homey and HomeKit don't have a "partial position" capability for garage doors, though.

**Comment by blutch32** [comment]
Ok I see. Then the only way for me to have this working is to change it as blind or as window covering. Then it work in HomeKit.

**Comment by blutch32** [comment]
Thanks a lot for your support btw. Is there any chance that this is implemented in homey in the future ? What should I ask to homey dev team ? To add a open/close/idle compatibility to homey for garage door ?

**Comment by robertklep** [comment]
The main issue is that HomeKit itself doesn't support such a state, so even if Homey would support it, HomeKitty cannot convert it to something similar on HomeKit.
