### ISSUE TITLE
Unsupported Device AQARA Wireless Switch Mini 

### ISSUE THREAD

**Issue by Domcuss** [robertklep/name.klep.homekitty#53]
AQARA Wireless Switch Mini, is supported Homekit, but with "old" Homey (Pro), not support.

### Type (brand/model) of device
Device AQARA Wireless Switch Mini 
### Homey Model
"old" Homey (Pro)

### Is it supported by HomeyKit?
Yes

### Device Classes

What are it's class, and virtual class (if it has one)?

* _Class_: button
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...ID: alarm_battery, measure_battery
* ...Title: Battery alarm, Battery
* ...Type: boolean, number

**Comment by robertklep** [comment]
It should be supported in the test version of HomeKitty.

**Comment by robertklep** [comment]
Either you're missing some capabilities, or the device isn't supported by HomeyKit, which requires that the device has a `button` capability (same goes for HomeKitty).

**Comment by Domcuss** [comment]
When connected to the aqara hub, the button is part of the apple homekit. But after connecting to homey, it cannot be transferred to apple homekit via homekitty. I would like to have everything connected to Homey only.

Is there a chance to get the button through homey to homekit?

**Comment by robertklep** [comment]
@PMeul1 my comment, one up from yours, states that it's not supported.

**Comment by PMeul1** [comment]
@robertklep Thanks for clarifying, I thought you were only talking about the '"old" Homey (Pro)'. 
It's clear to me now that it is also valid for the latest Homey Pro '23 . Can we do something to change that ('_I'm not sure if it's possible to make it work because of how Homey works with button devices_') ? 

Is this now valid for all buttons - or is there is certain brand or make that will show up in Apple home through Homey Pro '23 and homekitty?

**Comment by robertklep** [comment]
@PMeul1 the relevant part of my comment is _"The Homey device is missing required capabilities to make it work on Homey"_. You can ask the developer of the app that supports your device if there's a reason why they don't use the `button` capability for it (there might be a good reason).

It's not valid for all buttons, devices of device class `button` with capability `button` or capability `onoff` are supported by HomeKitty.

**Comment by PMeul1** [comment]
Hi @robertklep Robert,

Which (brand of) buttons will be visible in Homey as well as Apple Home, as far as you are aware?
I hope to get some concrete idea on this from your experience.

Regards, Philip

**Comment by robertklep** [comment]
I don't use Homey for home automation myself, so I have no idea which ones would work.

But what exactly do you want to achieve?
