### ISSUE TITLE
Koppelen van de nieuwe homey PRO

### ISSUE THREAD

**Issue by Rodestier** [robertklep/name.klep.homekitty#57]
De pairing code doet niks en als ik de qr code scan dan werkt het ook niet. Kan hier na gekeken worden? Ik weet niet hoe ik het anders moet koppelen en er word ook bijna niks over geschreven.

**Comment by robertklep** [comment]
Datgene dat er wél over is geschreven is best relevant: https://community.homey.app/t/app-pro-homekitty-aka-homeykit-3-0/72824#attention-homey-pro-2023-users-2

**Comment by daanhendriksen** [comment]
Hi, bij mij vindt hij ook niets. na een tijdje wachten komt hij met de melding dat de accessoire niet is gevonden.

**Comment by daanhendriksen** [comment]
alle stappen uitgevoerd maar mn telefoon blijft zeggen dat hij het accessoire niet kan vinden. nog andere ideeen?

**Comment by robertklep** [comment]
Hoe is je Homey aangesloten: via ethernet of via WiFi?

**Comment by daanhendriksen** [comment]
Ethernet

**Comment by daanhendriksen** [comment]
Allemaal gedaan. 
overigens werkt mijn p1 meter van homewizard ook niet en kan hij mijn shelly WiFi apparaten ook niet automatisch vinden. Deze moest ik handmatig toevoegen. 
alles draait op een asus modem zonder speciale configuratie en ik heb WiFi ap’s van ubiquiti gekoppeld via een unify controller geïnstalleerd op m’n synology. 

Kan het zijn dat daar problemen ontstaan?

**Comment by robertklep** [comment]
Dat zou kunnen, ja. Wat al die apparaten/apps met elkaar gemeen hebben is dat ze mDNS (multicast DNS) gebruiken om zichzelf vindbaar te maken op het netwerk, als dat voor meerdere apparaten niet werkt is de kans groot dat multicast uit staat (of verkeerd is ingesteld). Dat zou ergens in de Unify controller moeten staan.

**Comment by daanhendriksen** [comment]
Unifi controller er tussen uit gehaald en plots werkt alles, (behalve de p1 dongle van homewizard)
bedankt!!!
