### ISSUE TITLE
Device dissapearing from Homekit

### ISSUE THREAD

**Issue by itzbolsi** [robertklep/name.klep.homekitty#58]
Hi, my garage door controller has latly been dissapearing from homekit. Still in Homey app and working fine.
This has happened a couple of times now.

### Type (brand/model) of device
Aeotec garage door controller gen 5

### Homey Model
- [x] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [x] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: Lock
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ID: d4959de5-1ee2-4b3f-a9cc-984650819786
* Title: 
* Type:

**Comment by robertklep** [comment]
Please see [the list of common issues](https://community.homey.app/t/app-pro-homekitty-aka-homeykit-3-0/72824#common-issues-4), specifically the third item.
