### ISSUE TITLE
Please support air pressure (measure_pressure)

### ISSUE THREAD

**Issue by RickardDe** [robertklep/name.klep.homekitty#59]
(make sure you also edit the title)

### Type (brand/model) of device
Aqara Temperature And Humidity Sensor

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: sensor
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID | Title | Type 
measure_battery | Batteri | number 
measure_temperature | Temperatur | number
measure_pressure | Tryck | number 
measure_humidity | Luftfuktighet | number 
alarm_battery | Batterialarm | boolean

**Comment by robertklep** [comment]
I'm fairly sure that the HomeKit protocol doesn't support barometric pressure.

**Comment by RickardDe** [comment]
According to this article is looks like its supported, https://www.instructables.com/Connect-Your-RaspberryPI-to-the-BME280-Temperature/.

**Comment by robertklep** [comment]
_"Please note that the barometric pressure sensor is only visible in 3rd party homekit apps, and not in "Home"_

That's because it's not supported by the HomeKit protocol and someone made up their own definition that some third party apps support.

**Comment by RickardDe** [comment]
Bummer, thanks anyway.
Do you know if it is the same problem with battery state?
