### ISSUE TITLE
Please support battery status

### ISSUE THREAD

**Issue by RickardDe** [robertklep/name.klep.homekitty#60]
(make sure you also edit the title)

### Type (brand/model) of device
Aqara Temperature And Humidity Sensor

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: sensor
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID | Title | Type
measure_battery | Batteri | number
measure_temperature | Temperatur | number
measure_pressure | Tryck | number
measure_humidity | Luftfuktighet | number
alarm_battery | Batterialarm | boolean

From what I can find BatteryLevel and StatusLowBattery is part of HomeKit standard Characteristics, https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types.

**Comment by robertklep** [comment]
Try v2.2.2: https://homey.app/a/name.klep.homekitty/test/

**Comment by RickardDe** [comment]
BatteryLevel works perfect, I have checked 'Aqara Temperature And Humidity Sensor', 'Fibaro Flood Sensor' and 'Aeotec Multisensor 6'.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/6021b9c4-c355-4975-9a68-b66e26dafa7d)


I dont have a battery with low power so I cant check StatusLowBattery yet :-)


Many thanks!

**Comment by robertklep** [comment]
FWIW, the low battery level is hardcoded to 10%.

Thanks for testing!

**Comment by RickardDe** [comment]
_FWIW, the low battery level is hardcoded to 10%._

Do you mean in Homey or in Apple Home?
It is my understanding that Apple Home does not calculate the low battery warning itself, but trust the device to tell it to Apple Home.
https://www.reddit.com/r/HomeKit/comments/qd43lw/any_idea_how_to_change_the_low_battery/

So I thing the tree Charactaristics HMCharacteristicTypeBatteryLevel, HMCharacteristicTypeChargingState and HMCharacteristicTypeStatusLowBattery work in parallell to give the compleate expirience in Apple Home.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/936d9b4f-a431-4030-9900-c5a89df61d5d)

Can you please ha a look into it?

**Comment by robertklep** [comment]
> It is my understanding that Apple Home does not calculate the low battery warning itself, but trust the device to tell it to Apple Home.

That's correct, and that's how I've implemented it: when the battery level drops below 10%, HomeKitty raises a low battery warning to iOS.

Charging state is not something Homey provides.

**Comment by RickardDe** [comment]
_Charging state is not something Homey provides._

Oh, I thought 'alarm_battery | Batterialarm | boolean' was the device own (through Homey) indication for low battery = Apple Home HMCharacteristicTypeStatusLowBattery .

**Comment by robertklep** [comment]
Good point, `alarm_battery` should probably be used for low battery warnings if the device has it.

**Comment by robertklep** [comment]
v2.2.5 should use `alarm_battery` if the device has that capability: https://homey.app/a/name.klep.homekitty/test/

**Comment by RickardDe** [comment]
> v2.2.5 should use `alarm_battery` if the device has that capability: https://homey.app/a/name.klep.homekitty/test/

Great-

2.2.5 is now installed, but it is hard for me to test right now since i dont have any devices in Homey with alarm_battery = TRUE :-)
I will try to find som used batteries to try with.

Thanks!

**Comment by RickardDe** [comment]
> 2.2.5 is now installed, but it is hard for me to test right now since i dont have any devices in Homey with alarm_battery = TRUE :-) I will try to find som used batteries to try with.

I have now found an old battery.

**measure_battery** | Batteri | number | **17** |   | 16 minutes ago
**alarm_battery** | Batterialarm | boolean | **true** |   | 16 minutes ago

After a reboot of HomeyKitty I can now se indication of a low battery.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/7524228c-4713-4a70-988c-0659e90a4a94)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/85f5d0b2-75ca-42d2-ad8b-d711b7782b72)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/2114d8ee-fdbc-4c4e-bf56-dcafc481c40a)



Well done and many thanks!

**Comment by RickardDe** [comment]
Possible bug:

After I have replaced my low battery in my Aqara Temperature And Humidity Sensor the value changes correctly in Homey, but no change is visible in Apple Home, aka still "Low battery".


ID | Title | Type | Value | Set Value | Last Changed
measure_battery | Batteri | number | 100 |   | 15 hours ago
alarm_battery | Batterialarm | boolean | false |   | 15 hours ago

I now restarted HomeyKitty app and the "Low battery" warning in Apple Home was removed.


So, is there a problem with flow the change of the value?

**Comment by robertklep** [comment]
HK only provides the value to iOS that Homey provides. However, delayed updates are an issue with HomeKit in general, sometimes related to a Home hub needing a reboot, that's not something I can fix.

I'll see if I can create a virtual device with `alarm_battery` and see if that works. If so, then the issue is somewhere else.

**Comment by robertklep** [comment]
There was indeed an issue with the implementation, should be fixed in v2.2.7: https://homey.app/a/name.klep.homekitty/test/

**Comment by RickardDe** [comment]
> There was indeed an issue with the implementation, should be fixed in v2.2.7: https://homey.app/a/name.klep.homekitty/test/

Sorry for the delay in my response, but it is vaccation time here :-)


I have now tested with changing my battery to one with low power (17%).
HomeKitty synced both measure_battery and alarm_battery almost instantly to Apple Home, no need to restart HomeKitty anymore.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/00f7ae60-ca13-4f12-afaf-5f51d7a4ab76)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/3f4c79c4-d25a-4a68-a2e5-af8cd07692e5)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/e29df030-5fc8-4f9d-92e8-9f2bfc154726)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/a085e9c5-8a72-4ef2-bf84-88368404425f)



And same when I replaced the battery with one with higher power (43%), HomeyKitty synced the new values almost instantely. 

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/2a347084-1f79-432d-b8d4-31e2f9f3d43f)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/e65d2cc4-e11b-4914-8f70-ef5ca852bfa2)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/303dcb89-916f-4319-b348-f323bec529f1)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/623d09c0-510a-40da-8b45-668ee712e7bc)



Many thanks for the updates!

**Comment by robertklep** [comment]
Thanks for the feedback!
