### ISSUE TITLE
Please support alarm_tamper

### ISSUE THREAD

**Issue by RickardDe** [robertklep/name.klep.homekitty#61]
(make sure you also edit the title)

### Type (brand/model) of device
Fibaro flood Sensor (FGFS-101-PLUS)

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: Sensor
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID | Title | Type

measure_battery | Batteri | number
alarm_tamper | Sabotagelarm | boolean 
measure_temperature | Temperatur | number
alarm_water | Vattenalarm | boolean

From https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types

[let HMCharacteristicTypeStatusTampered: String](https://developer.apple.com/documentation/homekit/hmcharacteristictypestatustampered)
An indicator of whether an accessory has been tampered with.

**Comment by robertklep** [comment]
Check v2.2.3: https://homey.app/a/name.klep.homekitty/test/

**Comment by robertklep** [comment]
Whoops, I just pushed it to live instead...

**Comment by RickardDe** [comment]
Tamper works fine for the Flood sensor, many thanks.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/c67415aa-0f01-4d22-a061-1a567e254238)


Did yo enabled HMCharacteristicTypeStatusTampered only for Fibaro Flood Sensor, or for all Sensors?
Since i also have 'Aeotec Multisensor 6' which also have the ID alarm_tamper (in Homey), but for them there is no sign of tampering in the device in Apple Home.

**Comment by robertklep** [comment]
> Did yo enabled HMCharacteristicTypeStatusTampered only for Fibaro Flood Sensor, or for all Sensors?
> Since i also have 'Aeotec Multisensor 6' which also have the ID alarm_tamper (in Homey), but for them there is no sign of tampering in the device in Apple Home.

Only for water leak sensors at the moment. I think it should be relatively easy to add it to other sensors too, let me see.

**Comment by robertklep** [comment]
v2.2.4 (current test): https://homey.app/a/name.klep.homekitty/test/
