### ISSUE TITLE
Please support filter_time_left

### ISSUE THREAD

**Issue by RickardDe** [robertklep/name.klep.homekitty#62]
(make sure you also edit the title)

### Type (brand/model) of device
Systemair IAM modbus
(https://community.homey.app/t/app-pro-systemair/27862)

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: thermostat
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

target_temperature | Måltemperatur | number
measure_temperature | Temperatur | number
systemair_mode_iam | Mode | enum
systemair_fan_mode_iam | Fan mode | enum
systemair_mode_iam_ro | Mode | string
systemair_fan_mode_iam_ro | Fan mode | string
filter_time_left | Days before filter replacement | number
meter_saf_rpm | Supply air | number
meter_saf_reg_speed | Supply air | number
meter_eaf_rpm | Extract air | number
meter_eaf_reg_speed | Extract air | number 
measure_temperature.outdoor_air_temp | Outdoor air temperature | number
measure_temperature.supply_air_temp | Supply air temperature | number
measure_temperature.extract_air_temp | Extract air temperature | number
measure_temperature.overheat_temp | Overheat temperature | number
measure_humidity | Luftfuktighet | number 
eco_mode | ECO mode | boolean | false
systemair_fan_mode_iam_prev | Previous fan mode | string

https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types
If the number in 'filter_time_left' is positive then HMCharacteristicTypeFilterChangeIndication = [notNeeded].
If the number in 'filter_time_left' is zero or negative then HMCharacteristicTypeFilterChangeIndication = [Needed].

**Comment by robertklep** [comment]
This is a custom capability, which only exists (and is defined in) the Systemair app. I'm not inclined to support custom capabilities in HomeKitty, because Homey doesn't guarantee that a capability named `filter_time_left` in app A has the same meaning and definition of a capability named `filter_time_left` in app B (in other words: if I implement support for this capability, and there is another app that has a similarly named capability yet with a different meaning, this will cause problems for users of that other app).

**Comment by RickardDe** [comment]
> This is a custom capability, which only exists (and is defined in) the Systemair app. I'm not inclined to support custom capabilities in HomeKitty, because Homey doesn't guarantee that a capability named `filter_time_left` in app A has the same meaning and definition of a capability named `filter_time_left` in app B (in other words: if I implement support for this capability, and there is another app that has a similarly named capability yet with a different meaning, this will cause problems for users of that other app).

Bummer (again :-) )

Understandebla that you would like to work with only standard capabilities in Homey and standard charactaristics in HomeKit.
Do you know of a link where Homey have their standard capabilities listed?

**Comment by robertklep** [comment]
Here's a list of standard capabilities: https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html

**Comment by RickardDe** [comment]
> Here's a list of standard capabilities: https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html

Thanks.
