### ISSUE TITLE
Cannot download homekitty

### ISSUE THREAD

**Issue by Dakkie62** [robertklep/name.klep.homekitty#64]
Hello all, 

I am very new to homey pro. Just got the bridge installed and I am trying to make sense of it all.

I wanted to download the Homekitty app, but it says it's not compatible with my homey.
Is there something I am missing?

Thanks

**Comment by robertklep** [comment]
Do you have Homey Bridge or a Homey Pro? HomeKitty will only work on a Homey Pro.

**Comment by Dakkie62** [comment]
I am sorry. I only got the bridge. Thank you for your time
