### ISSUE TITLE
Feature Request: camera devices as cameras

### ISSUE THREAD

**Issue by empiric1** [robertklep/name.klep.homekitty#65]
Is it possible to add support for camera devices to be shown as actual cameras in Homekit?

At the moment they are viewed as motion detectors, so no picture is avalable. 

for instance I have Ring indoor cameras in Homey Pro 2019. 

Thanks in advance. 

* ...
* ...
* ...

**Comment by robertklep** [comment]
Homey doesn't support cameras in a meaningful way, so HomeKitty cannot either 😔

**Comment by empiric1** [comment]
Okey, I got your point. As I noted video streaming is poor. 

However screenshots is possible in Homey, which have been nice in Homekit. For instance to get a screenshot in the Apple TV how is at the front door ringing the doorbell :) 

can i contact Athom to improve this or have you already tried? 

Thanks for a great app!

**Comment by robertklep** [comment]
I looked at supporting snapshots once, but there was an issue with it (can't remember what exactly). I'll try and see if I can revive the code.

**Comment by robertklep** [comment]
I've taken a look again, and I don't see a way of supporting camera device for Homey, not even for snapshots.
