### ISSUE TITLE
Wemo doorbell - full homekit doorbell

### ISSUE THREAD

**Issue by labarten** [robertklep/name.klep.homekitty#66]
(Belkin) Wemo doorbell

For homey pro 2023

Not supported (yet) by homey kit

would be nice if could set my Sonos setup as a chime for my video doorbell, so only when the button is pressed that my Sonos speakers make a bell sound. 

Currently the wemo doorbell is not visible by homeykit.

**Comment by robertklep** [comment]
Please create a new issue using the "Feature request/Unsupported Device" template, it asks some relevant questions, otherwise I have no idea where to begin.
