### ISSUE TITLE
Homekitty with Onecta Daikin app

### ISSUE THREAD

**Issue by LouisGoud** [robertklep/name.klep.homekitty#67]
(make sure you also edit the title)

### Homekitty

I have installed Homekitty and bridge and devices are recognized by Homekit. In Homekit I can find the Daikin Onexta Airco devices but when I want to control the devices no response at all on the devices or in the Homey app. What can I do to make it work?

- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [x] Yes
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* ...
* ...
* ...

**Comment by robertklep** [comment]
Please follow the instructions posted [on the community forum](https://community.homey.app/t/app-pro-homekitty-aka-homeykit-3-0/72824#common-issues-4).
