### ISSUE TITLE
Unsupported fan from Device Capabilities / Advanced Virtual Device

### ISSUE THREAD

**Issue by RickardDe** [robertklep/name.klep.homekitty#68]
(make sure you also edit the title)

### Type (brand/model) of device
Device Capabilities / Advanced Virtual Device
https://homey.app/sv-se/app/nl.qluster-it.DeviceCapabilities/Device-Capabilities/

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: fan
* _Virtual Class_: N/A

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/768b557c-ebe2-4555-85bf-5fe08d49a794)

This advanced virtual device (FTX2) is shown as Unsupported in HomeKitty Device list.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/8f278553-db90-448e-a159-8d793321cb48)

When I create a simular fan via Virtual devices (FTX1) it is shown as supported.

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/400a978b-0e2e-472b-834a-befa97193e22)

![image](https://github.com/robertklep/name.klep.homekitty/assets/140390864/66b5960e-c122-400b-8096-62c78a3ef823)

Both the class (fan) and capabilities (onoff and dim) are the same so I think it should be supported.

**Comment by robertklep** [comment]
It probably _is_ supported, but the Device Capabilities app does a lot of dynamic capability juggling which is probably causing the problem. Have you tried enabling the device even though it's in the "unsupported" column?

**Comment by RickardDe** [comment]
Yes, I have tried to enabeling it, but the 'enable button' is locked.

**Comment by RickardDe** [comment]
Of all rookie mistakes ...
Thanks, a restart of HomeKitty moved 'FTX2' to ths supported column, and it shows up in Apple Home after enabling it.

Sorry for spending your time :-)

**Comment by robertklep** [comment]
No problem!

Restarting the app is only a temporary fix though because the next time you reboot your Homey it will probably happen again. In HomeKitty's App Settings you can configure a delay that HomeKitty will wait before it starts, which will allow Device Capabilities to do its jobs and (hopefully) be finished by the time HomeKitty finds its devices.
