### ISSUE TITLE
Thermostat (AC) - Missing Characteristic.Active (Power on/off)

### ISSUE THREAD

**Issue by ecointet** [robertklep/name.klep.homekitty#69]
### Type (brand/model) of device
Tuya device (using Tuya Cloud App) - AC Thermostat (Cool/Heat)

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: thermostat
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

- onoff | Turned on | boolean 
- target_temperature | Target temperature | number
- measure_temperature | Temperature | number
- thermostat_mode | Thermostat mode | enum

### Problem

The **onoff** capability is not transmitted to Homekit.
Probably because the **Characteristic.Active** is not set.

The workaround is when the thermostat mode is set to OFF, Homekit understand it is not active.
But it is not possible to just clic on the tile to turn the AC on/off. Not possible to use the "Turns On" automation.

In the video I can clic to toggle the AC (Bedroom 2) - (Homebridge)
But with Homekitty, the Living Room AC will open the tile and I have to change the mode.

![homekit](https://github.com/robertklep/name.klep.homekitty/assets/14220374/907972b6-0dff-4d22-845c-33c1f6d7f6d9)

**Comment by ecointet** [comment]
I found the plugin I am using in Homebridge is setting for all the devices (including AC) the **Characteristic.Active** status:
https://github.com/0x5e/homebridge-tuya-platform/blob/63ff35fff6af71cc46a79b751b96a9e3ff8d3db5/src/accessory/characteristic/Active.ts#L10

**Comment by robertklep** [comment]
The issue here is that your device is marked as a "thermostat", which makes HomeKitty use the [Thermostat service](https://github.com/homebridge/HAP-NodeJS/blob/93a9743c6ae5b6ba3cb4949ef418341234812226/src/lib/definitions/ServiceDefinitions.ts#L1484-L1505), which doesn't have an "Active" characteristic.

My guess is that your HomeBridge project doesn't use the `Thermostat` service but the `HeaterCooler` service, which _does_ have an "Active" characteristic.

Homey doesn't have a device class that matches `HeaterCooler` (there's only `heater`), so I'm not sure how I would be able to solve this in a way that doesn't break support for thermostat devices that _are_ thermostat.

**Comment by ecointet** [comment]
It makes sense, a Thermostat probably doesn't need to be turned off/on.

HeaterCooler service is much more pertinent because the current Thermostat service is also missing:

  *   Fan Speed
  *   On/Off capabilities (+ Automation)

Why not converting your integration to HeaterCooler? If the onoff parameter is not in Homey, the mode selected can help (off mode = not active; everything else = active).

Maybe the 2 services are probably very identical and nothing will be break. No special characteristics for Thermostat (?)

Otherwise, a way to change the device type in your configuration page? Probably relevant for many other use cases.

Thanks! Happy to help/test if needed.
——
Sent from my mobile device.
________________________________

**Comment by OlivierZal** [comment]
Maybe by creating a new map category and testing if the device belongs to `thermostat` **and** does not have `onoff` capability [somewhere before here](https://github.com/robertklep/name.klep.homekitty/blob/c0273d87e91fec58e497fc79d99588d9abf895d8/lib/device-mapper.js#L76)?

Sounds dirty but would be generic in the Homey context, given that it allows a `thermostat` not have the `onoff` capability.

**Comment by robertklep** [comment]
> HeaterCooler service is much more pertinent because the current Thermostat service is also missing...

HeaterCooler is much more pertinent _in your situation_, not in all the other situations where a "thermostat" device is actually just that: a thermostat device.

The main issue here is that Homey just doesn't have a proper device class for air conditioners, so app developers need to pick a device class that best matches the device they're implementing, in this case "thermostat".

> * Fan

Homey doesn't have fan speed or swing mode capabilities either 🤷🏼‍♂️

> Why not converting your integration to HeaterCooler?

Because even though they are similar, they aren't the same. Thermostat, for example, has a "target temperature" which makes a lot of sense for that type of device. So I can't to changing Thermostat to HeaterCooler and expect everything to work fine for all the other users out there.

> Otherwise, a way to change the device type in your configuration page? Probably relevant for many other use cases.

That might be something for a future update, but it's far from being a trivial addition, so don't wait for it.

Instead, if you want a button to turn on/off your AC, you can always use a virtual device for that.

**Comment by robertklep** [comment]
> Maybe by creating a new map category (`heatercooler`) and testing if the device belongs to `thermostat` **and** does not to have `onoff` capability [somewhere before here](https://github.com/robertklep/name.klep.homekitty/blob/c0273d87e91fec58e497fc79d99588d9abf895d8/lib/device-mapper.js#L76)?
> 
> Sounds dirty but would be generic in the Homey context, given that it allows a `thermostat` not to have the `onoff` capability.

So devices with class `thermostat` and the `onoff` capability would map to HeaterCooler? That's not a risk I'm going to take, because it wouldn't surprise me if there are proper thermostat devices that also have `onoff` capabilities that would break if I would implement such a map.

**Comment by robertklep** [comment]
I wonder if it doesn't make more sense to enhance [the current "heater" map"](https://github.com/robertklep/name.klep.homekitty/blob/main/lib/maps/heater.js) to _also_ support cooling.

Then use the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) to create a virtual device of class `heater` and some flows (or possibly Device Capabilities might be able to do this without flows, I don't know that app too well) to make it mirror the actual air conditioner device.

**Comment by ecointet** [comment]
First, Thank you for your support Robert! Much appreciated.

> My guess is that your HomeBridge project doesn't use the Thermostat service but the HeaterCooler service

I confirm, the device type used in [Homebridge is HeaterCooler](https://github.com/0x5e/homebridge-tuya-platform/blob/63ff35fff6af71cc46a79b751b96a9e3ff8d3db5/src/accessory/AirConditionerAccessory.ts#L179). It is the same for Heaters and ACs.

> I wonder if it doesn't make more sense to enhance [the current "heater" map](https://github.com/robertklep/name.klep.homekitty/blob/main/lib/maps/heater.js) to also support cooling

Homebridge did that actually, but the Tuya specs contain if it is a heater or ac...
From my point of view, the characteristics are very similar to Thermostat (target temperature, mode (cool, heat, auto, off), etc...). No need to change the mode depending of the temperature, we all prefer to select the right mode during winter or summer :)

> Then use the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) to create a virtual device of class heater

Not a big fan if this is not out of the box, my feeling is still the Thermostat type and HeaterCooler type are very similar, ACs are now working like a Thermostat, the Homekit approach is confusing. We should kill thermostats ^^

**Comment by OlivierZal** [comment]
> > Maybe by creating a new map category (`heatercooler`) and testing if the device belongs to `thermostat` **and** does not to have `onoff` capability [somewhere before here](https://github.com/robertklep/name.klep.homekitty/blob/c0273d87e91fec58e497fc79d99588d9abf895d8/lib/device-mapper.js#L76)?
> 
> > 
> 
> > Sounds dirty but would be generic in the Homey context, given that it allows a `thermostat` not to have the `onoff` capability.
> 
> 
> 
> So devices with class `thermostat` and the `onoff` capability would map to HeaterCooler? That's not a risk I'm going to take, because it wouldn't surprise me if there are proper thermostat devices that also have `onoff` capabilities that would break if I would implement such a map.
> 
> 
> 
> And to be honest, this whole issue started because it's not possible to turn on/off an air conditioner with a single tile press, or from an automation. That's not a massive issue that warrants a change that may cause problems for other users, and there are workarounds.

Agreed 👍

**Comment by OlivierZal** [comment]
> I wonder if it doesn't make more sense to enhance [the current "heater" map](https://github.com/robertklep/name.klep.homekitty/blob/main/lib/maps/heater.js) to _also_ support cooling (it uses the HeaterCooler service, and it should be possible to determine if the device is heating or cooling based on current and target temperatures and/or thermostat mode).
> 
> 
> 
> Then use the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) to create a virtual device of class `heater` and some flows (or possibly Device Capabilities might be able to do this without flows, I don't know that app too well) to make it mirror the actual air conditioner device.
> 
> 
> 
> I'd be willing to implement the required changes to the map, but I leave it up to others to make it work with Device Capabilities (or possibly another app that's more suited).

Your idea is much better than mine.

**Comment by ecointet** [comment]
>Then use the [Device Capabilities app](https://homey.app/a/nl.qluster-it.DeviceCapabilities/) to create a virtual device of class heater

To avoid another virtual device and app, can you differentiate a thermostat from an AC Controller, thanks to the  Homey spec "**driver**" ?

**In my case:**
Driver | homey:app:com.tuya.cloud — air-conditioner

If it contains "**air-conditioner**", you can use the HeaterCooler instead of Thermostat. ?

**Comment by robertklep** [comment]
> If it contains "**air-conditioner**", you can use the HeaterCooler instead of Thermostat. ?

I'm not inclined to add app-specific code to HomeKitty. I also don't see an easy (as in: not kludgy) way to add this to HomeKitty.

**Comment by ecointet** [comment]
noted! I think we checked all the possibilities :) 
I will use some workarounds to easily turn on/off the AC without having to "open the tile, then -> select the mode".
Thanks! this issue can be closed ^^
