### ISSUE TITLE
Philio Roller Shutters not supportet.

### ISSUE THREAD

**Issue by Dici71** [robertklep/name.klep.homekitty#7]
Philio Rollershutters seem not to be supported.

**Comment by robertklep** [comment]
Please find the device [here](https://tools.developer.homey.app/tools/devices) and post:
* its class
* its virtual class (if it has one)
* its capabilities

**Comment by Dici71** [comment]
Hi,
<img width="820" alt="Bildschirm­foto 2022-12-06 um 07 23 59" src="https://user-images.githubusercontent.com/90046346/205837181-7174bb62-685c-4b61-a481-0fa72208ceed.png">



<img width="1026" alt="Bildschirm­foto 2022-12-06 um 07 23 28" src="https://user-images.githubusercontent.com/90046346/205837235-7d088268-7488-4a4e-8605-593e843b0179.png">

**Comment by robertklep** [comment]
Ah yes, a window covering that uses `dim` 😭 

I left out support for these because window coverings shouldn't use "dim" to set their position, the correct capability is "windowcoverings_set". I was hoping app developers would have updated their apps to use that capability, but I guess not.

**Comment by Dici71** [comment]
Ok i understand ;-)

maybe it will be fixed in the future.....

is it possible to integrate the device anyway?

**Comment by robertklep** [comment]
Not with HomeKitty at the moment, because it doesn't support the "dim". You can still use HomeyKit for it though.

**Comment by Dici71** [comment]
> Not with HomeKitty at the moment, because it doesn't support the "dim". You can still use HomeyKit for it though.

that's what I do ;-))

**Comment by robertklep** [comment]
I'll let you know when HomeKitty supports it 👍🏻

**Comment by Dici71** [comment]
perfect....Thanks !!

**Comment by Dici71** [comment]
When i must use homeykit for my philio sensors it is necessary that homykit supports SDKv3 because i already ordered the new Homey pro.

**Comment by robertklep** [comment]
Try the current [test version of HomeKitty](https://homey.app/a/name.klep.homekitty/test).

**Comment by Dici71** [comment]
Works.....great support !!

**Comment by robertklep** [comment]
Good to hear!

**Comment by Dici71** [comment]
by the way....it seems that iOS 16.2 will be released soon. is HomeKitty ready for the new HomeKit structure ?
