### ISSUE TITLE
Add class "lock" (Smart Door Lock)

### ISSUE THREAD

**Issue by ecointet** [robertklep/name.klep.homekitty#70]
### Type (brand/model) of device
Bold Smart Lock

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [X] No
- [ ] I don't know

### Device Classes

* _Class_: lock
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* onoff | Turned on | boolean

**Comment by robertklep** [comment]
I wonder why a developer would use `onoff` instead of `locked`... 🤔

Anyway, try the test version of the app: https://homey.app/a/name.klep.homekitty/test/

**Comment by ecointet** [comment]
Hi! Thanks for the impressive reactivity 💪👌🏻
It works very well but it is inverted. Probably because of Homey / Bold (?).

For Home kit.
Onoff (true) = locked
Onoff (false) = unlocked

in Homey I have the opposite 🤨

i don’t know if you have to invert on your side or if I have to ask a bug fix to Bold.

So far it is not a big issue 😄 still nice. Thanks!

![IMG_1414](https://github.com/robertklep/name.klep.homekitty/assets/14220374/33000c9a-dc89-4c43-8098-e19b7e024e36)
![IMG_1415](https://github.com/robertklep/name.klep.homekitty/assets/14220374/d7944573-0504-4fba-b9f0-7fc5d9f88f36)

**Comment by robertklep** [comment]
I feared as much 🫣 I would think that "on" means "locked" and "off" means unlocked, but this app developer seems to do everything their own way...

I have turned it around in HomeKitty (and wait for another lock app that does it the other way, but I guess we'll just have to see then), but ideally, the app developer should fix their app. It would be best if they created a new driver and deprecate the old one.

Try v2.2.9 (current test): https://homey.app/a/name.klep.homekitty/test/

**Comment by ecointet** [comment]
Thanks! This is now perfect !

About the on/off it could make sense, in Homekit when it’s locked, it means nothing to highlight, the tile is « grey/off ». But when it is unlocked, it has to be highlighted (important info!).

After I turn on the lock through homekit, Bold will turn off the lock when it is locked back (back to normal it means I guess ☺️). Normal behavior 👌🏻

looks good so far, ticket closed ! So impressive.

![IMG_1417](https://github.com/robertklep/name.klep.homekitty/assets/14220374/6c65a42f-c1c7-47bb-93cb-e2f4ed961a5e)
![IMG_1416](https://github.com/robertklep/name.klep.homekitty/assets/14220374/3b24671b-e839-4983-acab-175eaa26a436)

**Comment by robertklep** [comment]
I e-mailed Bold to explain the situation and how to fix it on their end.
