### ISSUE TITLE
Add class TV (any smart TV)

### ISSUE THREAD

**Issue by ecointet** [robertklep/name.klep.homekitty#71]
### Type (brand/model) of device
Samsung Smart TV (Frame)

### Homey Model
- [X] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [X] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: tv
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* onoff | Turned on | boolean
* volume_up | Volume up | boolean 
* channel_up | Channel up | boolean
* volume_down | Volume down | boolean
* channel_down | Channel down | boolean
* volume_mute | Volume muted | boolean
* volume_set | Set volume | number

Expected result in Homekit:

![IMG_2461E2C17B9F-1](https://github.com/robertklep/name.klep.homekitty/assets/14220374/660801ae-c374-4bd6-a6b8-a782900ddc78)

**Comment by robertklep** [comment]
I'm looking to implement this, but not sure how to map the Homey capabilities to the HomeKit `RemoteKey` values: https://github.com/homebridge/HAP-NodeJS/blob/93a9743c6ae5b6ba3cb4949ef418341234812226/src/lib/definitions/CharacteristicDefinitions.ts#L3063

Any ideas?

**Comment by ecointet** [comment]
Not sure if someone is using the TV tile as a remote controller ( is this possible)?
On my side, as a first implementation, only the **Characteristic.Active** is enough!

Displaying the TVs with the status (on/off) and be able to turn it on or off with Homekit is good enough.

**Comment by ecointet** [comment]
> Thanks for your donation, by the way

You are welcome, a very very small contribution 😅

The TVs are displayed as regular switches and not as TVs (cf my screenshot above).

- There is 2 switches per TV as well, any reason ?

thanks!

![IMG_1426](https://github.com/robertklep/name.klep.homekitty/assets/14220374/cdc8e3ce-95eb-48d0-9cad-e2f143cd3b03)
![IMG_1427](https://github.com/robertklep/name.klep.homekitty/assets/14220374/841aabfe-3d83-435b-a749-b54144a7725a)

**Comment by robertklep** [comment]
I forgot to remove `tv` from the "generic `onoff` devices" list, so it was being mapped twice.

Fixed in v2.2.11: https://homey.app/a/name.klep.homekitty/test/

**Comment by ecointet** [comment]
Ah cool! Makes total sense :) now it is perfect :)
I have a new icon with a home for the TV, never seen thay before, why not 😜😂

thanks 🙏 

![IMG_1430](https://github.com/robertklep/name.klep.homekitty/assets/14220374/5e8e3f72-0d2e-4ebd-8e84-59c841e1c86b)
