### ISSUE TITLE
Cant get homekitty in homekit app

### ISSUE THREAD

**Issue by MaikelNL** [robertklep/name.klep.homekitty#72]
I cant get homekit to work with experimental en homekitty. I can set all devices lamps etc and i can set the bridge in homekit. It connects and want me to install all the lamps etc. When im done the lights in homekit etc are not connected it seems if the bridge isnt working. Reset apple tv / homekit and reset the homey and homekitty app often but nothing seems to work. Apple tv / iphone up to date and homey also up to date.

**Comment by robertklep** [comment]
If you can't get it to work in both the Experiment and in HomeKitty, it sounds like a local issue. Other that "reset everything" I cannot really offer much else.
