### ISSUE TITLE
Unsupported Device

### ISSUE THREAD

**Issue by SamCan92** [robertklep/name.klep.homekitty#73]
### Type (brand/model) of device
Eufy Cam (native Homekit). Please add Support that it's also shown in Homekit when added using the Eufy App in Homey. This way it'll be possible to use "crying detection" for example, which normally disappears when using it with homekit native.

### Homey Model
- [ ] "old" Homey (Pro)
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

**Comment by robertklep** [comment]
Homey doesn't (really) support cameras, so HomeKitty doesn't either.

It _might_ be possible to pass certain specific properties (like the crying detection you mentioned), but I need more information for that to assess if it's even possible:
* find the device on this page: https://tools.developer.homey.app/tools/devices
* please post the following here:
  * the device's class
  * the device's virtual class (if it has one)
  * for all capabilities, post their ID, title and type
