### ISSUE TITLE
[Feature Request/Homey bridge hub]

### ISSUE THREAD

**Issue by andreashenriksen1985** [robertklep/name.klep.homekitty#74]
(make sure you also edit the title)

### Type (brand/model) of device

2023 Athom Homey Bridge

### Homey Model
- [ ] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* Will your app HomeKitty someday be ported for the Homey Bridge?
* ...
* ...

**Comment by robertklep** [comment]
> * Will your app HomeKitty someday be ported for the Homey Bridge?

No, Homey Bridge doesn't support local network access and Athom doesn't allow community developers to develop apps for Homey Cloud/Bridge.
