### ISSUE TITLE
All Home devices remain in ‘updating’ status

### ISSUE THREAD

**Issue by MarkStoutjesdijk** [robertklep/name.klep.homekitty#75]
Hi, 
Since this morning, all my devices from the Homekitty bridge remain in ‘updating’ (Bijwerken cq Geen Reactie) in Home. As far as I know I didn’t do anything to cause this; no new config changes except maybe a name change of the bridge (in Home). 
Has there been an update perhaps?
Thanks,
Mark

**Comment by MarkStoutjesdijk** [comment]
![IMG_3397](https://github.com/robertklep/name.klep.homekitty/assets/26836533/fb3fb4d6-2179-4050-82b5-fc1137b8c1dc)

**Comment by robertklep** [comment]
> Has there been an update perhaps? Thanks, Mark

There haven't been any updates (of HomeKitty, at least), but check the [list of common issues](https://community.homey.app/t/app-pro-homekitty-aka-homeykit-3-0/72824#common-issues-4).
