### ISSUE TITLE
[Feature Request/Unsupported] Doorbird doorbell

### ISSUE THREAD

**Issue by miszterx** [robertklep/name.klep.homekitty#76]
### Type (brand/model) of device
Doorbird Doorbell 2101V https://www.doorbird.com/en/shop/?ean=4260423870567

### Homey Model
- [X ] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [X] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: doorbell
* _Virtual Class_: - 

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

ID | Title | Type | Value | Set Value | Last Changed
alarm_generic | Generic alarm | boolean | false |   | 1 day ago
alarm_motion | Motion alarm | boolean | false |   | 3 hours ago
button.notificationevents | Set URL's for notifications | boolean | null | truefalseSET |  
button.removenotificationevents | Remove notification URL's | boolean | null | truefalseSET |  
open_action | Trigger default relay (↑swipe up↑) | number | 0 | SET | 16 hours ago
open_action_2 | Trigger second relay (↑swipe up↑) | number | null | SET |  
open_action_3 | Trigger third relay (↑swipe up↑) | number | null | SET |  
open_action_4 | Trigger fourth relay (↑swipe up↑) | number | null | SET |  
open_action_5 | Trigger fifth relay (↑swipe up↑) | number | null | SET

In my case the open_action would be the preferable, I have just one relay.

**Comment by robertklep** [comment]
`open_action` is a custom capability, which HomeKitty doesn't support.

If you want this device to work, what you might be able to do is create a virtual device with a `button` capability, and in a flow trigger that capability from the `open_action` capabilities.

**Comment by miszterx** [comment]
Thanks for the feedback. 
I made it. Virtual device with a button, and it works as you mentioned.
I hope in the future homey will make a secretly promised apple integration so this will work with all the feature.
Thanks again.

**Comment by robertklep** [comment]
Homey has a "HomeKit Experiment", which is their Apple integration. But it doesn't support custom capabilities either, because (by definition) they are custom to one particular app and their definition only makes sense within the context of that app, not anywhere else (including HomeKit).
