### ISSUE TITLE
Shelly plus H&T [Feature Request/Unsupported]

### ISSUE THREAD

**Issue by glupschis-home** [robertklep/name.klep.homekitty#79]
(make sure you also edit the title)

### Type (brand/model) of device
Shelly plus H&T
https://www.shelly.com/de/products/shop/shelly-plus-h-t

...

### Homey Model
- [x ] "old" Homey (Pro)
- [x ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices
sensor

What are it's class, and virtual class (if it has one)?

* _Class_:
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)
See Attachment 

ID	Title	Type	Value	Set Value	Last Changed
measure_temperature	Temperatur	number	22.1		9 minutes ago
measure_humidity	Luftfeuchtigkeit	number	63.1		9 minutes ago
measure_battery	Batterie	number	100		1 week ago
measure_voltage	Spannung	number	6.15		9 minutes ago
rssi	Signal	number	-67		9 minutes ago
deviceGen2	Device Generation 2	string	null

**Comment by glupschis-home** [comment]
![IMG_1952](https://github.com/robertklep/name.klep.homekitty/assets/50011117/13022768-33cb-43a6-ad2d-160885bfe04d)
![IMG_1953](https://github.com/robertklep/name.klep.homekitty/assets/50011117/0871cd7f-5b43-47ca-9154-6cbe1511dd5b)

**Comment by robertklep** [comment]
This device should be supported already.

**Comment by robertklep** [comment]
It's shown as being exported to Home, so why it's not showing up, I don't know, but that's an issue with Home, not with HomeKitty.

If you have any Home hubs (Apple TV, HomePod), try rebooting them.

**Comment by glupschis-home** [comment]
Wow, thank you very much. There it is 🤗
It even shows the correct readings. But it doesn't show up in my Apple Home dashboard!😢

![IMG_1960](https://github.com/robertklep/name.klep.homekitty/assets/50011117/2385d8cc-8ed6-4bbd-a9eb-a2f026727672)

**Comment by robertklep** [comment]
That's because sensors aren't shown as tiles in Home 🤷🏼‍♂️

When you select the "Klima" category, you should see Temperature/Humidity:
<img width="238" alt="image" src="https://github.com/robertklep/name.klep.homekitty/assets/1190916/43cb2292-e222-4a38-9cfd-3f4db7673f6c">

Their values are coming from temperature/humidity sensors, like the H&T.

**Comment by glupschis-home** [comment]
Yes, that's how it is. I could just about understand it.

There is a HomePod mini in every room. These also have temperature sensors whose values are displayed there.
In the room where the Shelly plus H&T is now also located, two values are displayed.

![IMG_1965](https://github.com/robertklep/name.klep.homekitty/assets/50011117/b94cccc7-e0c8-4644-ae06-3b21875dc1e0)
![IMG_1966](https://github.com/robertklep/name.klep.homekitty/assets/50011117/90b98a05-86cf-4c27-9a8f-58945b816072)



I assumed that the Shelly plus H&T would be displayed in Apple Home in the same way as the HeatIt.

There is also no HomePod mini in the living room, but a first generation HomePod. This does not have a temperature sensor. Therefore, only one measured value is displayed here, namely that of the HeatIt.

![IMG_1967](https://github.com/robertklep/name.klep.homekitty/assets/50011117/ba1146c8-e93f-4612-b10b-d2acbd96d841)

Thank you very much for taking the time to explain this to me. ☺️


And thanks also for the really great Homie Kitty app.
I will support it 😀.

**Comment by robertklep** [comment]
The HeatIt is a thermostat, I think? Controllable devices like that are shown in a tile.

**Comment by glupschis-home** [comment]
Yes, it is 😊

**Comment by glupschis-home** [comment]
One last question. 
It has nothing to do with HomyKitti, but maybe you know: Can you use the temperature and humidity readings from a Homepod Mini in a Homey Flow?  I have not found a Homyapp for the Hompod.

**Comment by robertklep** [comment]
AFAIK that's not possible, no.
