### ISSUE TITLE
Homematic IP Suport

### ISSUE THREAD

**Issue by danbart2022** [robertklep/name.klep.homekitty#81]
(make sure you also edit the title)

### Type (brand/model) of device
Homematic Actor HM-LC-Bl1-FM

### Homey Model
- [ ] "old" Homey (Pro)
- [X] Homey Pro 2023

### Is it supported by HomeyKit?
- [X] Yes - BUT only by App
- [ ] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: Homematic Devices HM-LC-Bl1-FM

### Device Capabilities
Homematic IP Devices, Supported by Homey App
https://homey.app/de-de/app/de.twendt.homey.matic/Homematic/

**Comment by robertklep** [comment]
Can you post the device class and its capabilities? Those can be found here: https://tools.developer.homey.app/tools/devices (search for your particular device, then copy its class, its virtual class if it has one, and the names of the capabilities of the device).
