### ISSUE TITLE
Everspring dimmable plugs appear as on/of plugs

### ISSUE THREAD

**Issue by voodoomatz** [robertklep/name.klep.homekitty#83]
My dimmable power plugs appear in HomeKit as on/off plugs.
In Homey they are dimmable. In HomeKit not.
With Homey experimental HomeKit it was fine.

- Type (brand/model) of device
Everspring - Z-Wave dimmable Mini Plug AD147

- Is it supported by HomeyKit?
Yes, worked fine on (experimental) Homeykit, but problems with Homeykitty.

- Device details
1. Property | Value
Key	| Value
ID | d4ebe749-c5bb-40ab-b052-dbb1b13ad7e5
Name | Sofalampe
Class | socket
Driver | homey:app:com.everspring:AD147
Ready | Yes
Available | Yes
Warning | No
Custom icon | No

2. Data
Key	| Value
token | "7f091266-0ca2-42ea-8fef-6ceaf56b81d5"

3. Settings
Key	| Value
zw_node_id | "13"
zw_manufacturer_id | "96"
zw_product_type_id | "3"
zw_product_id | "3"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SWITCH_MULTILEVEL"
zw_device_class_specific | "SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL"
zw_firmware_id | "771"
zw_application_version | "1"
zw_application_sub_version | "1"
zw_hardware_version | "2"
zw_secure | "⨯"
zw_battery | "⨯"
zw_wakeup_interval | 0
zw_wakeup_enabled | false
zw_group_1 | "1"
zw_group_2 | ""
zw_application_version_1 | "0"
zw_application_sub_version_1 | "6"
meter_report_interval | 3
remember_state | true
dimming_onoff | false
energy_alwayson | false
energy_value_off | null
energy_value_on | null
zw_configuration_value | ""
homekit_exclude | false

5. Capabilities
ID | Title | Type | Value | Set Value | Last Changed
onoff | Eingeschaltet | boolean | true | truefalseSET | 15 minutes ago
dim | Dimmlevel | number | 0.02 | SET | 15 minutes ago

**Comment by voodoomatz** [comment]
Sigh .. I had to reset HomeKitty and lost all HomeKit automations related to the bridge.. Ah well..

So, this is what I found:
- With experimental HomeKit the dimmable plug presents in Home as a switch.
- HOWEVER, via voice command I can still dimm the plug / the plugged in light
- When using HomeKitty, the plug presents the same way but when using a voice command "dimm sofa light to 10%" I receive a reply "there's no device supporting this"
![Bildschirmfoto 2023-12-28 um 20 42 48](https://github.com/robertklep/name.klep.homekitty/assets/1741360/b9bdbda3-aea1-4bc2-abe5-b451bf979e50)
![Bildschirmfoto 2023-12-28 um 20 43 14](https://github.com/robertklep/name.klep.homekitty/assets/1741360/50eedf85-551d-4a8d-8560-dd7425e33957)
![Bildschirmfoto 2023-12-28 um 20 43 07](https://github.com/robertklep/name.klep.homekitty/assets/1741360/7eb60c15-c3fb-4bb6-817b-5bce3f0a30e4)

**Comment by robertklep** [comment]
Should be fixed with [v2.2.12](https://homey.app/a/name.klep.homekitty/test/).

Make sure that in Home, you set "Anzeigen als" to "Licht".

**Comment by voodoomatz** [comment]
CONFIRMED.

Thank you so much. Nice job, Rob!!

Sent from my mobile device. Please excuse my brevity.
________________________________
Von: Robert Klep ***@***.***>
Gesendet: Friday, December 29, 2023 2:53:10 PM
An: robertklep/name.klep.homekitty ***@***.***>
Cc: Marcel Korte ***@***.***>; Author ***@***.***>
Betreff: Re: [robertklep/name.klep.homekitty] Everspring dimmable plugs appear as on/of plugs (Issue #83)


Should be fixed with v2.2.12<https://homey.app/a/name.klep.homekitty/test/>.

Make sure that in Home, you set "Anzeigen als" to "Licht".

**Comment by robertklep** [comment]
Thank for for testing 😊
