### ISSUE TITLE
Dimmers showing as On/off lamps in homekit

### ISSUE THREAD

**Issue by runbert** [robertklep/name.klep.homekitty#84]
Hi,

I have a Nexa dimmer added on my homey pro which works just fine to dim from the homey app. The thing is that the dimmer-device shows ups as an on/off lamp in homekit with no possibility to dim. Any ideas why?

Otherwise the homeykitty app works great!

Thanks

**Comment by robertklep** [comment]
If you create an issue [using the Feature Request/Unsupported Device template](https://github.com/robertklep/name.klep.homekitty/issues/new?assignees=&labels=&projects=&template=feature-request-unsupported-device.md&title=%5BFeature+Request%2FUnsupported%5D), it will ask for information that I need to determine why your device isn't shown as expected.
