### ISSUE TITLE
[Unsupported] Nexa dimmer

### ISSUE THREAD

**Issue by runbert** [robertklep/name.klep.homekitty#85]
### Type (brand/model) of device
Nexa generic dimmer

### Homey Model
- [ ] "old" Homey (Pro)
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

### Device Classes
* _Class_: socket

### Device Capabilities
* dim
* Dimningsnivå
* number

**Comment by robertklep** [comment]
Doesn't the device also have an `onoff` capability?

**Comment by robertklep** [comment]
Outlets in Home cannot be dimmable, but in the Homey app, in the device settings, you can set configure the type of device that is plugged in. If you change that to "Light", and restart HomeKitty, it should appear as a dimmable light in Home.

You need to install the current test version of HomeKitty for that to work: https://homey.app/a/name.klep.homekitty/test/

**Comment by runbert** [comment]
Worked like a charm.

Thank you!
