### ISSUE TITLE
Ikea e27 white spectrum dimmable 1055 lumen light

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [robertklep/name.klep.homekitty#86]
Hi, I noticed after installing the light that Homekitty only exposes an on/off function to HomeKit. Wanted to let you know this is not s known issue 

Link to the product https://www.ikea.com/fi/fi/p/tradfri-led-lamppu-e27-1055-lm-aelylaite-langaton-himmennettaevae-valkoinen-spektri-pallo-60545673/

I will be installing the new models of Ikea Gu10 color bulbs tomorrow to see if the same issue remains. 

Thanks, love the app!

**Comment by robertklep** [comment]
Please open a new issue [with the correct template](https://github.com/robertklep/name.klep.homekitty/issues/new?assignees=&labels=&projects=&template=feature-request-unsupported-device.md&title=%5BFeature+Request%2FUnsupported%5D).

I don't have this device so have no idea how it is handled internally by Homey, and I need that information to see why dimming isn't supported.
