### ISSUE TITLE
[Feature Request Hue Dimmer Switch Gen 3]

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [robertklep/name.klep.homekitty#87]
(make sure you also edit the title)

### Type (brand/model) of device
Philips Hue Gen 3 Dimmer Switch

### Homey Model
- [ ] "old" Homey (Pro)
- [ x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [ x] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: remote
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

* 	6abbbc8f-4fba-4125-8392-d807767d42bb
* Dimmer Switch (Gen 3)
* remote

**Comment by robertklep** [comment]
Can you give the list of capabilities?

**Comment by AllSeeingGoatWizard** [comment]
Developer page states the following: CapabilitiesThis device has no capabilities.The app gives these options in Homey for the remote.I have these remotes exposed to HomeKit via Homebridge and Homebridge Hue plugin running all kinds of scenes.  Would be convenient to merge my Hue remotes to the same network and get rid of Homebridge.Robert Klep ***@***.***> kirjoitti 5.2.2024 kello 8.00:﻿
Can you give the list of capabilities?

**Comment by robertklep** [comment]
If a device has no capabilities, I'm afraid HomeKitty cannot do anything with it.
