### ISSUE TITLE
Issue with Heltun switches - status is not displayed properly in HomeKit

### ISSUE THREAD

**Issue by guglez** [robertklep/name.klep.homekitty#88]
Hi,

I'm facing two issues with Heltun Touchpanel switches and HomeKitty:
1. The status of the button is not reflected properly in homekitty. If the button is on - it's not reflected in homekit. If I press the button via homekit - it turns on succsessfully. But after some time the status of the button in HomeKit changes to off while the button actual state is on.
2. Heltun switch has 3 sensors - temperature, humidity and illuminance. It's not possible to see the data from the sensors in HomeKit.

### Type (brand/model) of device
Z-Wave Heltun Touch Panel switch
### Homey Model
- [ ] "old" Homey (Pro)
- [ Х] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [ x] I don't know

### Device Classes
* _Class_: button
* _Virtual Class_: N/A

### Device Capabilities
(see above for where you can find these; please post ID, title and type)
Buttons have the following capability:
* onoff

Master device (the switch itself has the following capabilities:
(it depends on a modell, switches may have from 1 to 5 buttons)
* heltun_scene_1	Button state 1 string
* heltun_scene_2	Button state 2 string
* heltun_scene_3	Button state 3 string
* heltun_scene_4	Button state 4 string
* heltun_scene_5	Button state 5 string
* button.reset_meter_power	Manually reset the power meter	boolean
* meter_power	Energy	number
* measure_temperature	Temperature	number
* measure_power	Power	number
* measure_luminance	Luminance	number
* measure_humidity	Humidity	number

**Comment by robertklep** [comment]
The issue with the `onoff` part is that HomeKitty treats button devices as stateless: a button is _pressed_, not _toggled_, so it doesn't have an on/off state. In my opinion, if the device has an `onoff` capability, it should have had a different device class (like `socket`). I can't really change this behaviour in HomeKitty because it will probably break button devices for other apps.

As for the sensors: HomeKitty does not know (and, AFAIK, cannot find out) which devices belong to each other, so it will treat each device separately. Since the button-devices don't have the sensor capabilities, they're not shown.

**Comment by guglez** [comment]
I wanted to share a bit more context regarding the challenges I'm currently experiencing with Heltun Touchpanel switches and HomeKitty.

The buttons on these switches have various states like hold, press, and double press, which are crucial for my home automation setup. Currently, I've noticed discrepancies in the state representation in HomeKit, especially during prolonged button presses. I believe this happening because HomeKit does not support such states.

Considering the importance of accurate on/off state representation for these buttons and the fact that I have around a hundred of them in my home, I was wondering if there might be a way to enhance this aspect of compatibility between Homey and HomeKit.

I understand the complexities involved in addressing such issues, and I truly appreciate the work you do with HomeKitty. I was wondering if there could be an option or setting, maybe something like "enable stateful buttons," that users could choose to activate based on their specific needs. Or maybe some other workarounds are possible?

This could potentially provide a solution for users like me who rely on the stateful nature of these buttons in Homey. I believe such a feature would not only greatly benefit my setup but could also enhance the overall user experience for others facing similar challenges.

Thank you for your time and consideration. I'm more than willing to collaborate or provide any additional information that might assist in addressing this matter. Looking forward to your insights and thoughts on this.

This looks odd to me, but the main device also has class "button":
![image](https://github.com/robertklep/name.klep.homekitty/assets/15347812/45130b1a-4c2b-45ea-bc4e-777dbc781c8e)


Here are the capabilities:
![image](https://github.com/robertklep/name.klep.homekitty/assets/15347812/c4a52906-967c-4190-88d1-d2cbce814574)

HomeKitty is my last hope. Original homey "Experiment" does not work with Heltun at all, devices are not visible in homekit and Athom refuses to provide support on that :(
