### ISSUE TITLE
Adding unsupported Xiaomi H3 air purifier

### ISSUE THREAD

**Issue by DamianPLN** [robertklep/name.klep.homekitty#89]
(make sure you also edit the title)

### Type (brand/model) of device
Xiaomi H3 air purifier

### Homey Model
- [ ] "old" Homey (Pro)
- [x ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ x] No
- [ ] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

Class | sensor

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

Capabilities
ID	Title	Type	Value	Set Value	Last Changed

airpurifier_zhimi_fanlevel	Fan Level	enum	1	
2 days ago

airpurifier_zhimi_mode	Mode	enum	3	
3 days ago

measure_temperature	Temperatura	number	22		1 hour ago

measure_humidity	Wilgotność	number	47		11 minutes ago

measure_pm25	PM2.5	number	11		4 minutes ago

onoff	Włączone	boolean	true	2 days ago

**Comment by robertklep** [comment]
The device should be mostly supported. However, fan level and mode are custom capabilities (specific to the app that you use) which HomeKitty doesn't support.

**Comment by DamianPLN** [comment]
Is there a chance this will change?

**Comment by robertklep** [comment]
No, sorry.
