### ISSUE TITLE
Aqara door sensor isn’t registering open or closed in HomeKit

### ISSUE THREAD

**Issue by Drag0n** [robertklep/name.klep.homekitty#9]

**Comment by basvdploeg** [comment]
I use multiple of those, and they work without a problem.

![aqara-aqara-door-window-sensor](https://user-images.githubusercontent.com/4628469/206261317-30d25cec-7d1d-4d7b-8c7c-3c8223e58f08.jpg)

**Comment by Drag0n** [comment]
> I use multiple of those, and they work without a problem.
> 
> ![aqara-aqara-door-window-sensor](https://user-images.githubusercontent.com/4628469/206261317-30d25cec-7d1d-4d7b-8c7c-3c8223e58f08.jpg)

Weird I just bought three off them and none of them shows when it’s open or closed in HomeKit. It works in Homey. 

You Dutch I see. Me too ;)

**Comment by robertklep** [comment]
@Drag0n I can't do anything with a "device X doesn't work" issue, I need more information if you want me to take a look at why it might not work.

There should be a "Feature request/Unsupported Device" template available when you want to create an issue which explains which details are relevant and how to obtain them.

**Comment by Drag0n** [comment]
> @Drag0n I can't do anything with a "device X doesn't work" issue, I need more information if you want me to take a look at why it might not work.
> 
> There should be a "Feature request/Unsupported Device" template available when you want to create an issue which explains which details are relevant and how to obtain them.

Done
