### ISSUE TITLE
Loevschall Multiple White Controller works properly in Homey, but shows up as on/off outlet in Apple Home

### ISSUE THREAD

**Issue by bjornand1** [robertklep/name.klep.homekitty#91]

**Comment by bjornand1** [comment]
I had no problems adding this LED spotlight controller to Homey, where I can change brightness and color. But in Apple Home, via Homekitty, it only shows up as an outlet that can be turned on/off. Is there any way to get it exported as a "full" light device?

**Comment by robertklep** [comment]
Please use the [feature request/unsupported device](https://github.com/robertklep/name.klep.homekitty/issues/new?assignees=&labels=&projects=&template=feature-request-unsupported-device.md&title=%5BFeature+Request%2FUnsupported%5D) template, that way I can check if there are more possibilities for this device.
