### ISSUE TITLE
[Feature Request/Unsupported] Loevschall Multiple White Controller works properly in Homey, but shows up as on/off outlet in Apple

### ISSUE THREAD

**Issue by bjornand1** [robertklep/name.klep.homekitty#92]
(make sure you also edit the title)

### Type (brand/model) of device
...Loevschall Multi White Controller

### Homey Model
- [x] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: socket
* _Virtual Class_:

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

![CleanShot 2024-03-23 at 17 07 14@2x](https://github.com/robertklep/name.klep.homekitty/assets/36516146/550ad300-c6b6-47dd-aedb-fe5b99ac88a0)

**Comment by robertklep** [comment]
I'm not sure why the developer chose to use "socket" as device class, it makes more sense as a "light".

For sockets, you can change the type of device that is plugged into it, in this case a light. This will change the virtual class and I think HomeKitty will then pick it up as a light.

To change, open the device in the mobile Homey app, then press the gear symbol in the top right corner, then change the "Plugged in" value.

**Comment by bjornand1** [comment]
As always, thanks for your quick response! I tried this, but nothing changed right away - is there anything I should do to refresh it from Homekitty?

**Comment by robertklep** [comment]
It might be required to restart the app, or the Home app on your iDevice.

**Comment by bjornand1** [comment]
Yes, that worked, all good now!
