### ISSUE TITLE
[Feature Request/Unsupported] - Denon AVR receiver

### ISSUE THREAD

**Issue by claessensbrent** [robertklep/name.klep.homekitty#94]
Hello, love your app, exposing many things to homekit for me. Only thing that is not working is my avr receiver. It shows up in homekit but says there it is unsupported. Is this somerhing you can help with? Thank you in advance!

### Type (brand/model) of device
Denon AVR-X1400H

### Homey Model
- [ ] "old" Homey (Pro)
- [x] Homey Pro 2023

### Is it supported by HomeyKit?
- [ ] Yes
- [ ] No
- [x] I don't know

### Device Classes
Find the device here: https://tools.developer.homey.app/tools/devices

What are it's class, and virtual class (if it has one)?

* _Class_: speaker
* _Virtual Class_: /

### Device Capabilities
(see above for where you can find these; please post ID, title and type)

clear_queue Afspeellijst Wissen boolean
music_source Muziek Bron string
onoff Aangezet boolean
volume_down Volume omlaag boolean
volume_up Volume omhoog boolean
volume_mute Gedempt volume boolean
volume_set Set volume number
speaker_playing Afspelenboolean
speaker_shuffle Shuffle boolean
speaker_repeat Repeat enum
speaker_position Positie number speaker_next Volgende boolean
speaker_prev Vorigeboolean
speaker_artist Artiest string
speaker_album Album string
speaker_track Track string

**Comment by robertklep** [comment]
I can reproduce the issue but all the required characteristics for a Speaker device in Home are supported by HomeKitty, so I have no idea why it says it's not supported. Perhaps for speakers Home requires a device that can also handle audio streams, in which case it's never going to work because Homey doesn't support streams.

**Comment by claessensbrent** [comment]
Hmm, thats a pitty…

I can try to reset the receiver and set it back up from scratch, can this have an impact or will it never work in your opinion?

Do you see any way to expose it with less capability? For me it would already be of great value if i can just expose the power and volume control.

Thanks in advance!

**Comment by robertklep** [comment]
No, that won't make a difference, for some reason Home just has an issue with it. I'll have to look at other implementations to see if I'm missing something.

**Comment by robertklep** [comment]
Ah, I found the issue: https://github.com/homebridge/homebridge/issues/3313#issuecomment-1411217107

Apparently, the Speaker service that I'm using can only be part of a doorbell accessory, which in this situation it's clearly not. I'll see if I can use the SmartSpeaker class instead.

**Comment by claessensbrent** [comment]
That seems hopefull… thanks in advance, I will keep an eye on coming updates.

**Comment by claessensbrent** [comment]
Hi Robert, any update on this? Did this make one of the updates or is it in planning? Thanks in advance.

**Comment by robertklep** [comment]
Apologies for not getting back.

It's not possible to make this work with HomeKitty, SmartSpeakers require a particular HomeKit setup that HomeKitty doesn't support 🙁
