### ISSUE TITLE
Homekitty not working

### ISSUE THREAD

**Issue by empiric1** [robertklep/name.klep.homekitty#98]
Homekitty v 2.2.7 does not communicate with homekit. Most devices (most of them are Shelly and IKEA) are not responding. 

I have restarted my Homey Pro (2019), homekitty app and my router without any result.

**Comment by robertklep** [comment]
This is still a local issue.

Do you have any home hubs, like an Apple TV or HomePods? If so, reboot those as well.

**Comment by empiric1** [comment]
Hi

My ATV which is primary hub is rebooted, as well as my two homepod mini.

Other users seems to have similar issue. For one of them installing latest test-version solved it. I just tried the same with several reboot of the homey, hubs and app, without any success.

Any idea please?

Many thanks in advance

Med vänlig hälsning,
Patrik

6 juli 2024 kl. 06:05 skrev Robert Klep ***@***.***>:

﻿

This is still a local issue.

Do you have any home hubs, like an Apple TV or HomePods? If so, reboot those as well.

**Comment by robertklep** [comment]
The issue isn't with the app, it's either with Homey itself (which has, historically, has had very unstable networking) or your network setup (for instance using VLAN's or separate IoT networks). I can't do anything about that.

**Comment by robertklep** [comment]
What you can try: restart your Homey, wait about 15 minutes (so all apps can start and everything gets settled), then try if you can reach the devices from the Home app in iOS. If not, create a diagnostics report for HomeKitty in the Homey app (please refer to this conversation so I can recognise it). I'll see if anything points to why you have this issue.

**Comment by empiric1** [comment]
Hi

Thanks!

I deleted the app in Homey and the Homekitty-bridge in homekit (Home app). I lost automations in Homekit, which where few since i so most in Homey.

I re-installed Homekitty and the bridge in Homekit. Now it works again. I will send you a report if the issue occurs again, hopefully not :)



8 juli 2024 kl. 06:21 skrev Robert Klep ***@***.***>:

﻿

What you can try: restart your Homey, wait about 15 minutes (so all apps can start and everything gets settled), then try if you can reach the devices from the Home app in iOS. If not, create a diagnostics report for HomeKitty in the Homey app (please refer to this conversation so I can recognise it). I'll see if anything points to why you have this issue.
